// Consolidated Vocabulary Dictionary for EKA SIR
// All duplicates removed, sorted, and categorized by class level

const dictKG1 = [
  // A-Z (2 basic words per letter)
  "APPLE", "ANT", "BALL", "BAT", "CAT", "CAR", "DOG", "DUCK", "EGG", "EAR",
  "FISH", "FROG", "GIRL", "GOAT", "HAT", "HAND", "ICE", "INK", "JAM", "JAR",
  "KITE", "KEY", "LION", "LEG", "MAN", "MAP", "NET", "NOSE", "OWL", "ONION",
  "PIN", "PEN", "QUEEN", "QUILT", "RAT", "RING", "SUN", "STAR", "TOY", "TREE",
  "UMBRELLA", "UNCLE", "VAN", "VEST", "WAGON", "WORM", "XRAY", "XYLOPHONE", "YAK", "YARN", "ZEBRA", "ZOO",

  // 12 Colors
  "RED", "BLUE", "GREEN", "YELLOW", "ORANGE", "PURPLE", "PINK", "BROWN", "BLACK", "WHITE", "GRAY", "VIOLET",

  // Days of the Week
  "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY",

  // Months of the Year
  "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER",

  // Counting 1 to 20
  "ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN",

  // ISLAMIAT
   "ALLAH", "QURAN", "PROPHET", "MOSQUE", "PRAYER", "FAITH", "GOOD", "KIND", "SHARE", "HELP"

 ];

const dictKG2 = [
  // A-Z EXPANDED (2 progressive words per letter)
  "ACORN", "ANVIL", "BRIDGE", "BUBBLE", "CLOUD", "CRAYON", "DRESS", "DREAM",
  "EAGLE", "EARTH", "FENCE", "FLAME", "GLOVE", "GRASS", "HORSE", "HEART",
  "IGLOO", "ISLAND", "JUNGLE", "JUMP", "KNEE", "KNIFE", "LEMON", "LIGHT",
  "MOON", "MOUTH", "NEST", "NURSE", "OCEAN", "ORCHID", "PLANE", "PENCIL",
  "QUIET", "QUEST", "RIVER", "ROCKET", "SHIRT", "SNOW", "TRAIN", "TIGER",
  "UNDER", "UNLOCK", "VALLEY", "VIOLIN", "WHALE", "WIND", "X-RAY", "X-MAS",
  "YARD", "YOGURT", "ZIPPER", "ZONE",

  // ACTION VERBS (Physical & Cognitive Progression)
  "CLIMB", "CRAWL", "CARRY", "CHASE", "CATCH", "BUILD", "BREAK", "FIX",
  "SORT", "MATCH", "COUNT", "MEASURE", "LISTEN", "SPEAK", "ASK", "ANSWER",
  "WAIT", "FOLLOW", "CHOOSE", "CREATE",

  // DESCRIPTIVE WORDS & OPPOSITES
  "TALL", "SHORT", "WIDE", "NARROW", "HEAVY", "LIGHT", "ROUGH", "SMOOTH",
  "WET", "DRY", "WARM", "COOL", "FULL", "EMPTY", "ROUND", "SQUARE",
  "STRAIGHT", "CROOKED", "STRONG", "WEAK",

  // NATURE & ENVIRONMENT
  "TREE", "LEAF", "ROOT", "SEED", "SOIL", "ROCK", "CAVE", "HILL",
  "MOUNTAIN", "BUSH", "LAKE", "POND", "OCEAN", "ISLAND", "FOREST", "DESERT",
  "SWAMP", "MEADOW", "GARDEN", "STREAM",

  // HOME, SCHOOL & COMMUNITY
  "KITCHEN", "BEDROOM", "BATHROOM", "GARAGE", "ATTIC", "BASEMENT", "WINDOW", "DOOR",
  "FLOOR", "CEILING", "WALL", "ROOF", "CHIMNEY", "FENCE", "GATE", "PATH",
  "BRIDGE", "TOWER", "LIBRARY", "MARKET",

  // BODY & SENSES
  "ELBOW", "WRIST", "ANKLE", "SHOULDER", "CHEEK", "CHIN", "FOREHEAD", "PALM",
  "FINGER", "TOENAIL", "EYEBROW", "EYELASH", "TONGUE", "TEETH", "GUMS", "NECK",
  "BACK", "STOMACH", "HIP", "SKIN",

  // TIME, WEATHER & SEASONS
  "MORNING", "NOON", "NIGHT", "DAWN", "DUSK", "TODAY", "YESTERDAY", "TOMORROW",
  "WEEK", "MONTH", "YEAR", "SPRING", "SUMMER", "AUTUMN", "WINTER", "SUNNY",
  "CLOUDY", "RAINY", "WINDY", "SNOWY",

  // SOCIAL, LOGIC & DAILY ROUTINES (28 words to reach exactly 200)
  "FRIEND", "FAMILY", "TEACHER", "STUDENT", "NEIGHBOR", "DOCTOR", "NURSE", "RULE",
  "PROMISE", "SURPRISE", "GIFT", "PARTY", "GAME", "RACE", "PRIZE", "CHAMPION",
  "BREAKFAST", "LUNCH", "DINNER", "SNACK", "SCHOOL", "RECESS", "REST", "WAKE",
  "BATH", "BRUSH", "DRESS", "COAT",

 "ELEVEN", "TWELVE", "THIRTEEN", "FOURTEEN", "FIFTEEN", "SIXTEEN", "SEVENTEEN", "EIGHTEEN", "NINETEEN", "TWENTY",

// 🕌 ISLAMIAT BASICS (Kid-Friendly)
  "ALLAH", "QURAN", "PROPHET", "MOSQUE", "PRAYER", "FAITH", "GOOD", "KIND", "SHARE", "HELP"

];

const dictClass1 = [

"ACE", "ACT", "ADD", "AGE", "AIR", "ALL", "AND", "ANT", "ANY", "APPLE",
  "ARM", "ASK", "BAD", "BAG", "BALL", "BAT", "BED", "BEE", "BELL", "BIG",
  "BIN", "BIRD", "BOAT", "BOOK", "BOX", "BOY", "BUS", "CAKE", "CAN", "CAP",
  "CAR", "CAT", "COW", "CUP", "DAD", "DAY", "DID", "DIG", "DOG", "DOLL",
  "DOT", "DRY", "DUCK", "DUG", "EAT", "EGG", "END", "EYE", "FAN", "FAR",
  "FAT", "FED", "FEW", "FIG", "FIN", "FISH", "FIT", "FLY", "FORK", "FOX",
  "FUN", "GET", "GIRL", "GOT", "GUM", "GUN", "HAD", "HAS", "HAT", "HEN",
  "HIM", "HIS", "HIT", "HOP", "HOT", "HUG", "ICE", "INK", "JAM", "JAR",
  "JET", "JOB", "JOY", "KEY", "KID", "KIT", "KITE", "LAB", "LAD", "LEG",
  "LET", "LID", "LIP", "LOG", "LOT", "LOW", "MAN", "MAP", "MAT", "MEN",
  "MOM", "MOP", "MUD", "MUG", "MUM", "NAP", "NET", "NEW", "NOD", "NOT",
  "NOW", "NUT", "OAT", "ODD", "OLD", "ONE", "OUT", "OWL", "OWN", "PAN",
  "PAT", "PEN", "PET", "PIG", "PIN", "POT", "PUP", "RAN", "RAT", "RED",
  "RIG", "RIP", "ROD", "RUG", "RUN", "SAD", "SAG", "SAT", "SAY", "SEE",
  "SET", "SIX", "SKY", "SUN", "TAP", "TAX", "TEA", "TEN", "THE", "TOY",
  "TRY", "TUB", "TUG", "TWO", "USE", "VAN", "VET", "WAG", "WAN", "WEB",
  "WET", "WIN", "WIT", "YAM", "YES", "YET", "YOU", "ZAP", "ZOO",

  "ABLE", "ACID", "ACTS", "AIDE", "AIRS", "ALSO", "AREA", "ARMS", "AWAY", "BABY",
  "BACK", "BAKE", "BALL", "BAND", "BANK", "BARN", "BATH", "BEAM", "BEAN", "BEAR",
  "BELL", "BEND", "BEST", "BIRD", "BITE", "BLUE", "BOAT", "BODY", "BONE", "BOOK",
  "BOOM", "BORN", "BOTH", "BOWL", "BUDS", "BUMP", "BURN", "BUSH", "BUTS", "BUZZ",
  "CAKE", "CALM", "CAME", "CAMP", "CANE", "CARE", "CART", "CASE", "CASH", "CAVE",
  "CELL", "CHAIR", "CHIP", "CHOP", "CITY", "CLAP", "CLAY", "CLEAN", "CLIMB", "CLOCK",
  "CLOSE", "CLOUD", "CLOWN", "CLUB", "COAT", "COIN", "COLD", "COME", "COOK", "COOL",
  "CORN", "COST", "COTE", "COTS", "COZY", "CRAB", "CRAWL", "CROP", "CROW", "CUBE",
  "CUPCAKE", "CURL", "CUTE", "DANCE", "DARK", "DATE", "DAWN", "DEAL", "DEEP", "DEER",
  "DESK", "DICE", "DISH", "DISK", "DOCK", "DOES", "DOLL", "DONE", "DOOR", "DOVE",
  "DOWN", "DRAG", "DRAW", "DREAM", "DRESS", "DRIP", "DROP", "DRUM", "DUCK", "DUST",
  "DUTY", "EACH", "EARLY", "EARS", "EASE", "EAST", "EASY", "EDGE", "EGGS", "EIGHT",
  "ELBOW", "ELSE", "EMPT", "ENDS", "EVEN", "EVER", "EYES", "FACE", "FACT", "FAIR",
  "FALL", "FARM", "FAST", "FEAR", "FEED", "FEEL", "FEET", "FELL", "FENCE", "FETCH",
  "FEVER", "FEW", "FIELD", "FIGHT", "FILE", "FILL", "FILM", "FIND", "FINE", "FIRE",
  "FISH", "FIVE", "FLAG", "FLAP", "FLAT", "FLEA", "FLED", "FLEW", "FLIP", "FLOCK",
  "FLOOR", "FLOW", "FLYING", "FOAM", "FOG", "FOOD", "FOOL", "FOOT", "FORK", "FORM",
  "FORT", "FOUR", "FOWL", "FOXES", "FREE", "FRESH", "FROG", "FROM", "FRONT", "FROST",
  "FRUIT", "FULL", "FUNNY", "FUR", "GAME", "GATE", "GAVE", "GEAR", "GEMS", "GIFT",
  "GIRL", "GIVE", "GLAD", "GLASS", "GLEN", "GLUE", "GOAL", "GOAT", "GOLD", "GONE",
  "GOOD", "GOOF", "GOOSE", "GRAB", "GRAD", "GRAM", "GRASS", "GRAY", "GREAT", "GREEN",
  "GREW", "GRIP", "GROW", "GULP", "GUMS", "GUN", "GUY", "HAIR", "HALF", "HALL",
  "HAND", "HANG", "HAPPY", "HARD", "HARK", "HARM", "HARP", "HATE", "HAVE", "HAWK",
  "HEAD", "HEAL", "HEAR", "HEAT", "HELD", "HELL", "HELP", "HERB", "HERE", "HERO",
  "HIDE", "HIGH", "HIKE", "HILL", "HINT", "HIRE", "HISS", "HIVE", "HOBBY", "HOLD",
  "HOLE", "HOME", "HONK", "HOPE", "HORN", "HORSE", "HOST", "HOTEL", "HOUR", "HOUSE",
  "HOWL", "HUGS", "HULL", "HUMP", "HUNG", "HUNT", "HURT", "HUSH", "HUTS", "ICE",
  "IDEA", "IGLOO", "ILL", "INCH", "INTO", "IRON", "ISLE", "ITCH", "ITEM", "IVY",
  "JACK", "JAIL", "JAM", "JAW", "JAZZ", "JEAN", "JEEP", "JELLY", "JEST", "JEWEL",
  "JIFFY", "JIG", "JINX", "JOB", "JOCK", "JOEY", "JOG", "JOIN", "JOKE", "JOLLY",
  "JOLT", "JOT", "JOWL", "JOY", "JUG", "JUICE", "JUMP", "JUNK", "JURY", "JUST",
  "KEEN", "KEEP", "KEPT", "KICK", "KID", "KILL", "KIND", "KING", "KISS", "KITE",
  "KNEE", "KNELT", "KNEW", "KNIFE", "KNOT", "KNOW", "LAB", "LACK", "LAD", "LADY",
  "LAKE", "LAMB", "LAME", "LAMP", "LAND", "LANE", "LAP", "LARK", "LASH", "LAST",
  "LATE", "LAUGH", "LAW", "LAWN", "LAZY", "LEAD", "LEAF", "LEAK", "LEAN", "LEAP",
  "LEARN", "LEAST", "LEAVE", "LED", "LEFT", "LEG", "LEND", "LENS", "LESS", "LET",
  "LEVEL", "LEVER", "LID", "LIE", "LIFE", "LIFT", "LIGHT", "LIKE", "LIME", "LINE",
  "LINK", "LION", "LIP", "LIST", "LIT", "LIVE", "LOAD", "LOAF", "LOAN", "LOB",
  "LOCK", "LOFT", "LOG", "LONE", "LONG", "LOOK", "LOOP", "LOOSE", "LORD", "LOSE",
  "LOSS", "LOST", "LOT", "LOUD", "LOVE", "LOW", "LUCK", "LUMP", "LUNCH", "LUNG",
  "LURE", "LUSH", "MAD", "MADE", "MAGIC", "MAID", "MAIL", "MAIN", "MAKE", "MALE",
  "MALL", "MAN", "MANY", "MAP", "MARCH", "MARK", "MART", "MASK", "MAST", "MAT",
  "MATCH", "MATE", "MATH", "MAZE", "MEAL", "MEAN", "MEAT", "MEET", "MELT", "MEMO",
  "MEND", "MENU", "MERE", "MESH", "MESS", "MICE", "MID", "MILD", "MILE", "MILK",
  "MILL", "MIND", "MINE", "MINI", "MINT", "MINTY", "MIRE", "MIST", "MIX", "MOAN",
  "MOB", "MOCK", "MODE", "MOLE", "MOM", "MONK", "MOON", "MOOR", "MORE", "MORN",
  "MOTH", "MOTOR", "MOUND", "MOURN", "MOUSE", "MOUTH", "MOVE", "MOW", "MUD", "MUG",
  "MULE", "MUM", "MUSH", "MUST", "MUTE", "MUTTON", "MYTH", "NAIL", "NAME", "NAP",
  "NARROW", "NASTY", "NATURE", "NAVAL", "NEAR", "NEAT", "NECK", "NEED", "NEST",
  "NET", "NEW", "NEWS", "NEXT", "NICE", "NIGHT", "NINE", "NO", "NOBLE", "NOBODY",
  "NOISE", "NONE", "NOON", "NOR", "NORTH", "NOSE", "NOTE", "NOTICE", "NOVEL", "NOW",
  "NUDGE", "NULL", "NUMB", "NUN", "NUT", "OAK", "OAR", "OAT", "OBEDIENT", "OBEY",
  "OBJECT", "OBLONG", "OBSERVE", "OBTAIN", "OBVIOUS", "OCCUR", "OCEAN", "OCTOBER",
  "ODD", "ODOR", "OF", "OFF", "OFFER", "OFTEN", "OH", "OIL", "OKAY", "OLD", "ON",
  "ONCE", "ONE", "ONLY", "ONTO", "OPEN", "OPERATE", "OPINION", "OPPOSITE", "OR",
  "ORANGE", "ORBIT", "ORDER", "ORDINARY", "ORGAN", "ORIGIN", "ORNAMENT", "OTHER",
  "OUR", "OUT", "OUTER", "OUTLINE", "OUTPUT", "OUTSIDE", "OVAL", "OVER", "OWN",
  "OWNER", "OX", "OXYGEN", "PARK", "PLAY", "RAIN", "RIDE", "ROAD", "ROCK", "ROPE",
  "SAID", "SHIP", "SHOP", "SING", "SKIN", "SNOW", "SOFT", "SONG", "STAR", "STOP",
  "SWIM", "TALL", "TENT", "TREE", "WALK", "WASH", "WIND", "WISH",

    // 🔢 MATH FOUNDATIONS
    "ADDITION", "SUBTRACTION", "MULTIPLY", "DIVIDE", "EQUAL", "GREATER", "LESSER", "FRACTION",
    "HALF", "QUARTER", "WHOLE", "NUMBER", "COUNT", "PATTERN", "SEQUENCE", "SHAPE",
    "CIRCLE", "SQUARE", "TRIANGLE", "RECTANGLE", "CORNER", "SIDE", "LENGTH", "WIDTH",

    // 🔬 SCIENCE OBSERVATION
    "ANIMAL", "PLANT", "WATER", "AIR", "LIGHT", "SOUND", "HEAT", "COLD",
    "GROW", "CHANGE", "LIVE", "DIE", "BIRTH", "DEATH", "FOOD", "ENERGY",

    // 💬 COMMUNICATION SKILLS
    "HELLO", "PLEASE", "THANKS", "SORRY", "YES", "NO", "QUESTION", "ANSWER",
    "SPEAK", "LISTEN", "READ", "WRITE", "SPELL", "SENTENCE", "WORD", "LETTER",

    // 🕌 ISLAMIAT: FAITH & PRACTICE
    "BELIEF", "WORSHIP", "CHARITY", "FAST", "PILGRIM", "PROPHET", "SCRIPTURE", "GUIDANCE",
    "MERCY", "FORGIVENESS", "PATIENCE", "GRATITUDE", "TRUTHFUL", "HONEST", "KINDNESS", "COMPASSION"

];

const dictClass2 = [
  // A-Z ACADEMIC EXPANSION (52)
  "ACCIDENT", "ACHIEVEMENT", "BROADCAST", "BUDGET", "CIRCUMSTANCE", "COLLABORATION", "DEMONSTRATION", "DETERMINATION",
  "ELEVATION", "ENCOURAGEMENT", "FOUNDATION", "FREQUENCY", "GENERATION", "GEOGRAPHY", "HARMONY", "HYPOTHESIS",
  "IMAGINATION", "INNOVATION", "JOURNALISM", "JUSTICE", "KINETIC", "KNOWLEDGE", "LITERACY", "LOGIC",
  "METAPHOR", "MECHANISM", "NAVIGATION", "NUTRITION", "OBSERVATION", "OPPORTUNITY", "PARTICIPATION", "PERSPECTIVE",
  "QUESTIONNAIRE", "QUANTITY", "RESEARCH", "RESILIENCE", "STRATEGY", "SYMMETRY", "TECHNOLOGY", "TERMINOLOGY",
  "UNDERSTANDING", "URBAN", "VARIATION", "VENTURE", "WISDOM", "WORKFORCE", "XENIAL", "XEROX",
  "YIELD", "YOUNGSTER", "ZENITH", "ZODIAC",

  // COGNITIVE & ACADEMIC VERBS (30)
  "ANALYZE", "APPLY", "ASSESS", "CALCULATE", "CATEGORIZE", "CLARIFY", "COLLABORATE", "COMPARE",
  "CONCLUDE", "CONSTRUCT", "CONTRAST", "DEBATE", "DEDUCE", "DEMONSTRATE", "DESCRIBE", "DETECT",
  "DIFFERENTIATE", "DISTRIBUTE", "ELABORATE", "EVALUATE", "EXCHANGE", "EXPAND", "EXTRACT", "FORMULATE",
  "IDENTIFY", "IMPLEMENT", "INFER", "INTERPRET", "PREDICT", "REFLECT",

  // COMPLEX & ABSTRACT ADJECTIVES (30)
  "ABUNDANT", "ANALYTICAL", "AUTHENTIC", "BRILLIANT", "COMPLEX", "CONCRETE", "CONSISTENT", "CRITICAL",
  "DECISIVE", "DETAILED", "DYNAMIC", "EFFICIENT", "ELABORATE", "ESSENTIAL", "EXPLICIT", "FLEXIBLE",
  "FRUITFUL", "GENUINE", "GRADUAL", "HARMONIOUS", "INNOVATIVE", "INTENSE", "LOGICAL", "MASSIVE",
  "MINIMAL", "OBJECTIVE", "PRECISE", "RELATIVE", "STRATEGIC", "SUBSTANTIAL",

  // ADVANCED MATH & DATA LITERACY (40)
  "ABSTRACT", "AVERAGE", "CALIBRATE", "COLUMN", "COMPARISON", "COORDINATE", "DECIMAL", "DENOMINATOR",
  "DIVISION", "EQUATION", "EQUIVALENT", "ESTIMATION", "EXPRESSION", "FACTOR", "FORMULA", "GEOMETRY",
  "INVERSE", "MIDPOINT", "MULTIPLE", "NUMERATOR", "OPERATOR", "PARALLEL", "PERIMETER", "PERPENDICULAR",
  "PROBABILITY", "PRODUCT", "QUOTIENT", "REMAINDER", "SYMMETRY", "VARIABLE", "AREA", "CUBE",
  "DIMENSION", "FACTORIAL", "FRACTION", "GRAPH", "INTEGER", "MEAN", "MEDIAN", "MODE",

  // LIFE SCIENCE & EARTH SYSTEMS (40)
  "ADAPTATION", "AMPHIBIAN", "ATOMIC", "BIOLOGY", "CAMOUFLAGE", "CELL", "CHEMISTRY", "CIRCUIT",
  "CONDENSATION", "CONSERVATION", "CRATER", "CRYSTAL", "DENSITY", "DIFFUSION", "ECOSYSTEM", "ELASTICITY",
  "EQUATOR", "EVAPORATION", "EXPERIMENT", "FILAMENT", "FRICTION", "GEOLOGY", "GERMINATION", "GRAVITATION",
  "HABITAT", "MAGNETISM", "METEOR", "MOLECULE", "ORGANISM", "PHOTOSYNTHESIS", "BACTERIA", "BIOSPHERE",
  "CATALYST", "COMPASS", "CONDUCTION", "EVOLUTION", "GENETICS", "HYBRID", "INERTIA", "LAVA",

  // SOCIAL STUDIES & HISTORY (25)
  "ANCESTRY", "CIVILIZATION", "COLONY", "CONSTITUTION", "CULTURE", "DEMOCRACY", "ECONOMY", "EMPIRE",
  "EXPLORER", "HERITAGE", "HISTORIAN", "INDUSTRY", "LEGEND", "MIGRATION", "MONARCHY", "MYTHOLOGY",
  "NOMAD", "ORIGIN", "PIONEER", "RELIGION", "REPUBLIC", "TRADITION", "TREATY", "TRADE", "VOYAGE",

  // LITERACY & LANGUAGE ARTS (25)
  "ALLEGORY", "ARGUMENT", "BIOGRAPHY", "CHARACTER", "CLIMAX", "CONFLICT", "CONTEXT", "DIALOGUE",
  "DICTIONARY", "DRAFT", "ENCYCLOPEDIA", "FICTION", "FORESHADOWING", "GENRE", "GRAMMAR", "INFORMATIONAL",
  "METAPHOR", "NONFICTION", "PLOT", "PUNCTUATION", "RESOLUTION", "STANZA", "SYLLABLE", "THEME", "VOCABULARY",

  // HEALTH, SAFETY & WELLNESS (20)
  "ALLERGY", "ANTIBIOTIC", "BANDAGE", "CALCIUM", "DIAGNOSIS", "EMERGENCY", "EXERCISE", "FIRST-AID",
  "HYGIENE", "IMMUNIZATION", "INSULATION", "MEDICATION", "NUTRIENT", "POSTURE", "PREVENTION", "PULSE",
  "QUARANTINE", "REHABILITATION", "SANITATION", "THERAPY",

  // TECHNOLOGY & DIGITAL LITERACY (20)
  "ALGORITHM", "BANDWIDTH", "BROWSER", "CODE", "DATABASE", "DIGITAL", "DOWNLOAD", "ENCRYPTION",
  "HARDWARE", "INTERFACE", "INTERNET", "KEYBOARD", "NETWORK", "PASSWORD", "PROGRAM", "SERVER",
  "SOFTWARE", "STREAMING", "UPLOAD", "VIRTUAL",

  // ARTS, MUSIC & EXPRESSION (20)
  "ACRYLIC", "BALLET", "BRONZE", "CANVAS", "CHORAL", "COMPOSITION", "CONDUCTOR", "CRAFT",
  "DESIGN", "EXHIBITION", "FRESCO", "IMPROVISATION", "MOSAIC", "ORCHESTRA", "PALETTE", "PORTRAIT",
  "SCULPT", "TEMPO", "THEATER", "WATERCOLOR",

  // GRAMMAR, LOGIC & TRANSITION WORDS (18)
  "ALTHOUGH", "BECAUSE", "BETWEEN", "CONSEQUENTLY", "DESPITE", "DUE", "EITHER", "EXCEPT",
  "FURTHERMORE", "HENCE", "HOWEVER", "INSTEAD", "MEANWHILE", "MOREOVER", "NEITHER", "OTHERWISE",
  "PROVIDED", "THEREFORE",

  // CHARACTER, VALUES & ETHICS (30)
  "ACCOUNTABILITY", "COMPASSION", "COURAGE", "EMPATHY", "GRATITUDE", "HONOR", "INTEGRITY", "JUDGMENT",
  "KINDNESS", "LOYALTY", "PATIENCE", "RESPECT", "RESPONSIBILITY", "TOLERANCE", "TRUST", "WISDOM",
  "CURIOSITY", "DILIGENCE", "FAIRNESS", "FORTITUDE", "GENEROSITY", "HUMILITY", "PERSISTENCE", "PRUDENCE",
  "SELFLESSNESS", "SINCERITY", "STEADFASTNESS", "UNSELFISHNESS", "VERACITY", "VIGILANCE",

    // A-Z EXPANDED (52)
    "ALBUM", "ANCHOR", "BADGE", "BASKET", "CABIN", "CANDLE", "DOLLAR", "DANCER",
    "EAGLE", "EARTH", "FABLE", "FARMER", "GARDEN", "GLASS", "HARVEST", "HELMET",
    "INSECT", "INSTRUMENT", "JIGSAW", "JOURNEY", "KETTLE", "KANGAROO", "LADDER", "LANTERN",
    "MAGNET", "MARBLE", "NATURE", "NECKLACE", "ORBIT", "OLIVE", "PADDLE", "PAINTING",
    "QUARTZ", "QUEST", "RABBIT", "RANGER", "SADDLE", "SAUCER", "TICKET", "TOMATO",
    "UNIFORM", "UPSTAIRS", "VALLEY", "VINE", "WALNUT", "WALRUS", "YACHT", "YOUTH",
    "ZINC", "ZODIAC", "XENON", "XYLEM",

    // VERBS & ACTIONS (25)
    "ADJUST", "ARRANGE", "BALANCE", "BELIEVE", "COMPARE", "CONSTRUCT", "DELIVER",
    "DESCRIBE", "DISCOVER", "EXPLORE", "EXPLAIN", "GATHER", "IMAGINE", "IMPROVE",
    "INVESTIGATE", "MEASURE", "OBSERVE", "ORGANIZE", "PRACTICE", "PREPARE", "RECORD",
    "REVIEW", "SHIELD", "SHARE", "SOLVE",

    // ADJECTIVES & EMOTIONS (25)
    "AFRAID", "AMUSED", "ANXIOUS", "BRIGHT", "CALM", "CHEERFUL", "CLEAN",
    "CONFUSED", "CURIOUS", "DELICATE", "DULL", "EXCITED", "FLAT", "FRAGILE",
    "GENTLE", "HONEST", "JEALOUS", "LOUD", "MATURE", "NERVOUS", "PAINFUL",
    "PROUD", "QUIET", "SILENT", "SHINY",

    // MATH & MEASUREMENT (25)
    "ADDITION", "ANGLE", "AREA", "BAR", "CHART", "CIRCLE", "CORNER", "COUNT",
    "CUBE", "DIAMETER", "DIVIDE", "EQUAL", "ESTIMATE", "FACTOR", "FRACTION", "GRAPH",
    "HALF", "LENGTH", "MINUS", "NUMBER", "PATTERN", "PLUS", "SEQUENCE", "SHAPE",
    "SUM",

    // SCIENCE & NATURE (25)
    "ANIMAL", "ATMOSPHERE", "BRANCH", "BUD", "CLIMATE", "CROP", "ECHO", "ENERGY",
    "ENVIRONMENT", "FOSSIL", "HABITAT", "HEAT", "LIGHTNING", "MATTER", "MINERAL", "MIXTURE",
    "MOTION", "NUTRIENT", "PLANT", "POLLUTION", "POWER", "ROOT", "SEASON", "SOIL",
    "SOLUTION",

    // GEOGRAPHY & COMMUNITY (25)
    "AIRPORT", "CAMPUS", "CAPITAL", "CHURCH", "CITY", "CONTINENT", "COUNTRY", "FACTORY",
    "FARM", "GLOBE", "HARBOR", "HIGHWAY", "LAKE", "LAND", "MAP", "MUSEUM",
    "NEIGHBORHOOD", "PARK", "PATH", "PEOPLE", "PLACE", "POPULATION", "REGION", "TOWN",
    "VILLAGE",

    // FOOD & NUTRITION (25)
    "APRICOT", "AVOCADO", "BANANA", "BREAD", "BUTTER", "CEREAL", "CHEESE", "CHICKEN",
    "CRACKER", "DATE", "DESSERT", "EGGPLANT", "FRUIT", "GRAIN", "GRAPE", "HONEY",
    "JUICE", "LETTUCE", "MEAT", "MILK", "MUSHROOM", "OATMEAL", "PASTA", "PEACH",
    "PEPPER",

    // TRANSPORTATION & TOOLS (25)
    "AIRPLANE", "AMBULANCE", "BICYCLE", "BOAT", "CAB", "CANOE", "CART", "DRILL",
    "FERRY", "HAMMER", "HELICOPTER", "HOSE", "JEEP", "LORRY", "MOTORCYCLE", "RAKE",
    "SAW", "SCISSORS", "SCOOTER", "SHOVEL", "SKATES", "SLED", "SUBWAY", "TRAM",
    "TRUCK",

    // FAMILY, ROLES & OCCUPATIONS (25)
    "AUNT", "BROTHER", "CITIZEN", "COACH", "COOK", "COUSIN", "DENTIST", "DRIVER",
    "ENGINEER", "FATHER", "FIREFIGHTER", "JUDGE", "LAWYER", "MOTHER", "OFFICER", "PILOT",
    "PARENT", "POLICE", "PRESIDENT", "SCIENTIST", "SINGER", "SISTER", "TRADER", "VETERINARIAN",
    "WORKER",

    // SCHOOL & LEARNING (20)
    "ANSWER", "ATTEND", "CLASS", "DESK", "DRAW", "ERASE", "EXAM", "GRADE", "HOMEWORK",
    "KNOW", "LEARN", "LESSON", "MARK", "NOTE", "NOTEBOOK", "PAPER", "QUIZ", "READ",
    "SPELL", "STUDY",

    // QUESTION & FUNCTION WORDS (20)
    "ABOUT", "AFTER", "ALONG", "AROUND", "BECAUSE", "BEFORE", "BETWEEN", "DURING",
    "EACH", "EVERY", "HOW", "INSIDE", "MANY", "OUTSIDE", "SINCE", "THROUGH",
    "UNTIL", "WHICH", "WITHIN", "WITHOUT",

    // TIME & SEQUENCE (8)
    "ALREADY", "EARLY", "FINALLY", "FIRST", "LATER", "LAST", "NEXT", "SOON"
];

const dictClass3 = [
  // A-Z ACADEMIC CONCEPTS (52)
  "ACCURACY", "ADAPTATION", "AESTHETICS", "ALGORITHM", "ANALOGY", "APPRECIATION", "ARCHITECTURE", "ARGUMENT", "AUTONOMY",
  "BIODIVERSITY", "BOUNDARY", "BREAKTHROUGH", "BUREAUCRACY",
  "CATALYST", "CHRONOLOGY", "CITIZENSHIP", "CLASSIFICATION", "COHERENCE", "COLLABORATION", "CONCEPT", "CONSCIOUSNESS",
  "DEMOCRACY", "DEMOGRAPHICS", "DETERMINISM", "DIVERSITY",
  "EMERGENCE", "ENVIRONMENT", "EQUILIBRIUM", "ETHICS",
  "FOUNDATION", "FRAGMENTATION", "FREQUENCY",
  "GEOMETRY", "GRADIENT", "GOVERNANCE",
  "HIERARCHY", "HYPOTHESIS", "HUMANITIES",
  "ILLUMINATION", "INFRASTRUCTURE", "INSIGHT", "INTERDISCIPLINARY",
  "JURISDICTION", "JUSTICE",
  "KINETICS", "KNOWLEDGE",
  "LINGUISTICS", "LITERACY",
  "METACOGNITION", "METHODOLOGY", "MINERALOGY",
  "NARRATIVE", "NEUROLOGY", "NOMENCLATURE",
  "OBSERVATION", "OPTIMIZATION", "ORIENTATION",
  "PARADIGM", "PERSPECTIVE", "PHENOMENON", "PREDICTION",
  "QUANTITATIVE", "QUORUM",
  "REFLECTION", "REGULATION", "RESONANCE",
  "SCAFFOLDING", "SEMANTICS", "STRATIFICATION", "SYNTHESIS",
  "TAXONOMY", "THEORETICAL", "TRANSFORMATION",
  "UTILIZATION", "URBANIZATION",
  "VALIDATION", "VARIATION", "VERIFICATION", "VIRTUALIZATION",
  "WATERSHED", "WEATHERING",
  "ZOOLOGY", "ZONING",

  // HIGHER-ORDER COGNITIVE VERBS (30)
  "ABSTRACT", "ACCUMULATE", "ACCELERATE", "AMPLIFY", "ANTICIPATE", "APPRAISE", "ASCERTAIN", "AUGMENT",
  "CALIBRATE", "CIRCUMVENT", "CLARIFY", "COMMUNICATE", "COMPOSE", "COMPREHEND", "CONCEIVE", "CONSOLIDATE",
  "CORRELATE", "CRITIQUE", "DECOMPOSE", "DELINEATE", "DERIVE", "DISSECT", "ELUCIDATE", "EMPHASIZE",
  "ENHANCE", "ESTABLISH", "EXEMPLIFY", "FACILITATE", "GENERATE", "INTEGRATE",

  // ANALYTICAL DESCRIPTORS & MODIFIERS (30)
  "ACCLAIMED", "ACUMEN", "ADAPTIVE", "ALTRUISTIC", "ANTHROPOGENIC", "ARDUOUS", "AUTONOMOUS", "BENEVOLENT",
  "CAPACIOUS", "COGNITIVE", "COMPREHENSIVE", "CONSEQUENTIAL", "CONTINGENT", "CONVERGENT", "DEDUCTIVE", "DELETERIOUS",
  "DIMINISHING", "DIVERSE", "DYNAMIC", "EMPIRICAL", "EXPONENTIAL", "FUNCTIONAL", "HETEROGENEOUS", "HYPOTHETICAL",
  "IMPLICIT", "INCLUSIVE", "INDICATIVE", "INHERENT", "INTERMEDIATE", "LEXICAL",

  // ADVANCED MATHEMATICS & DATA LITERACY (45)
  "ABSCISSA", "ALGEBRA", "APPROXIMATION", "ARITHMETIC", "ASCENDING", "BINOMIAL", "CARTESIAN", "CIRCUMFERENCE",
  "COEFFICIENT", "CONGRUENT", "CONSTANT", "COORDINATES", "CORRELATION", "CUBE", "DECIMAL", "DENOMINATOR",
  "DERIVATIVE", "DIAMETER", "DIFFERENCE", "DISCRETE", "DIVISOR", "EQUATION", "EQUIVALENT", "ESTIMATION",
  "EXPONENT", "FACTORIAL", "FRACTION", "GEOMETRIC", "GRAPH", "HISTOGRAM", "HYPOTENUSE", "INTEGER",
  "INTERVAL", "ISOSCELES", "MEAN", "MEDIAN", "MODE", "MULTIPLIER", "NUMERATOR", "ORDINATE",
  "PERPENDICULAR", "POLYGON", "PROBABILITY", "PRODUCT", "QUOTIENT", "RADIUS", "RATIO", "REMAINDER",
  "SEQUENCE", "STATISTIC", "SUMMATION", "TANGENT", "VARIABLE", "VECTOR", "VOLUME", "WEIGHT",
  "ZENITH",

  // PHYSICAL & LIFE SCIENCES (40)
  "ABSORPTION", "ACCELERATION", "ADAPTIVE", "AEROBIC", "ANATOMY", "ANTIBODIES", "ASYMMETRY", "BIOMASS",
  "BIOME", "CAPILLARY", "CARBOHYDRATE", "CELLULAR", "CHEMICAL", "CIRCULATORY", "CLASSIFY", "COMBUSTION",
  "CONDENSATION", "CONDUCTOR", "CONSERVATION", "CONVECTION", "DENSITY", "DIFFUSION", "DISSECT", "ELECTRICITY",
  "ENZYME", "EVOLUTION", "EXPERIMENT", "FILTRATION", "GENETICS", "GERMINATION", "HEAT", "HORMONE",
  "INVERTEBRATE", "MAGNETISM", "METABOLISM", "MUSCLE", "NERVE", "ORGAN", "PHOTOSYNTHESIS", "PROTEIN",
  "RESPIRATION", "SKELETON", "SYNAPSE", "TISSUE", "VACCINE", "VERTEBRATE", "VIRUS",

  // EARTH, SPACE & ENVIRONMENTAL SYSTEMS (35)
  "ATMOSPHERE", "BEDROCK", "BIOMIMICRY", "CANYON", "CLIMATE", "COMET", "CONTINENTAL", "CRUST",
  "DEBRIS", "DEPRESSION", "ECLIPSE", "ELEVATION", "EROSION", "FOSSIL", "GEOTHERMAL", "GLACIER",
  "GRAVITY", "HEMISPHERE", "HORIZON", "HYDROLOGY", "LUNAR", "MANTLE", "METEOROLOGY", "MIGRATION",
  "MONSOON", "OZONE", "PLATE", "PRECIPITATION", "RECYCLE", "RECYCLING", "SATELLITE", "SEDIMENT",
  "SEISMIC", "SOLAR", "THERMODYNAMICS", "TIDAL", "TROPICAL", "TSUNAMI", "WATERCYCLE", "WIND",

  // CIVICS, ECONOMICS & GLOBAL STUDIES (35)
  "AMENDMENT", "BALANCE", "BUDGET", "CAPITAL", "CURRENCY", "DEFICIT", "DELEGATE", "ELECTION",
  "EMIGRATION", "EXPENDITURE", "EXPORT", "FEDERATION", "INFLATION", "INFRASTRUCTURE", "INVESTMENT",
  "JUDICIARY", "LEGISLATION", "MARKET", "MIGRATION", "MONOPOLY", "NATIONALISM", "PARLIAMENT",
  "POLICY", "PRODUCTION", "PROFIT", "PROPOSAL", "PROVIDER", "REFERENDUM", "REGULATION", "REPRESENTATION",
  "RESOURCE", "REVENUE", "SANCTION", "SUPPLY", "TARIFF", "TAXATION", "TREATY", "UNION",

  // LANGUAGE ARTS, COMPOSITION & RHETORIC (40)
  "ABRIDGED", "ALLITERATION", "AMBIGUITY", "ANTAGONIST", "ANTITHESIS", "APOLOGY", "APPEAL", "ARGUMENTATIVE",
  "ASSESSMENT", "BIOGRAPHY", "CENSUS", "CLAUSE", "CLIMAX", "CONNOTATION", "CONTEXTUAL", "DEBATE",
  "DENOTATION", "DESCRIPTIVE", "DIAGRAM", "DIALECT", "DIALOGUE", "DRAFT", "EDITING", "ELABORATION",
  "EPILOGUE", "EVIDENCE", "EXCERPT", "EXPOSITION", "FIGURATIVE", "FORESIGHT", "GENRE", "IDIOM",
  "IMAGERY", "INFERENCE", "INTERPRETATION", "INTRODUCTORY", "LITERARY", "MANUSCRIPT", "METAPHOR", "NARRATOR",
  "ONTOLOGY", "OUTLINE", "PARAPHRASE", "PERSUASIVE", "PLOT", "POETRY", "PREMISE", "PROTAGONIST",
  "PUNCTUATION", "RHETORIC", "RHETORICAL", "SIMILE", "STRUCTURE", "STYLE", "SUMMARIZE", "SYMBOLISM",
  "THEME", "TONE", "TRANSITION", "VERBOSITY", "VOICE",

  // TECHNOLOGY, ENGINEERING & DIGITAL SYSTEMS (35)
  "ALGORITHM", "APPLICATION", "ARCHITECTURE", "AUTOMATION", "BANDWIDTH", "BINARY", "CIRCUIT", "CLOUD",
  "CODE", "COMPILATION", "COMPRESS", "DATABASE", "DEBUG", "DIGITIZE", "DOWNLOAD", "DRONE",
  "ENCRYPTION", "FIRMWARE", "HARDWARE", "HAPTIC", "INTERFACE", "INTERNET", "LATENCY", "MAINFRAME",
  "NETWORK", "OPTICAL", "PROTOCOL", "ROBOTICS", "SERVER", "SIMULATION", "SOFTWARE", "STREAMING",
  "TELEMETRY", "TERABYTE", "UPLOAD", "VIRTUAL", "WIRED", "WIRELESS", "WORKSTATION",

  // HEALTH, PSYCHOLOGY & HUMAN DEVELOPMENT (35)
  "ADOLESCENCE", "ANXIETY", "APPETITE", "AUTONOMY", "BEHAVIOR", "CALCIUM", "CARDIOVASCULAR", "COGNITION",
  "DEVELOPMENT", "DIET", "DOPAMINE", "ENDOCRINE", "EMOTION", "EMPLOYEE", "ENVIRONMENTAL", "EXERCISE",
  "FEVER", "FLEXIBILITY", "GENETICS", "GROWTH", "HEALTH", "HEARING", "HORMONES", "IMMUNITY",
  "INFANCY", "INJURY", "INSULIN", "MENTAL", "METABOLISM", "MOTOR", "NEUROLOGICAL", "NUTRITION",
  "PERCEPTION", "PHYSIOLOGY", "PUBERTY", "RESILIENCE", "RESPIRATORY", "SENSORY", "STRESS",

  // CRITICAL THINKING, LOGIC & ARGUMENTATION (35)
  "ANALYSIS", "ASSUMPTION", "BIAS", "CAUSALITY", "COHERENCE", "CONJECTURE", "CONSENSUS", "CONTRADICTION",
  "CORRELATION", "CRITERIA", "DEDUCTION", "DISCOURSE", "DISPUTE", "DISTINCTION", "DOUBT", "EVALUATION",
  "EVIDENCE", "EXAMINATION", "FALLACY", "HYPOTHESIS", "ILLOGICAL", "IMPLICATION", "INDUCTION", "INQUIRY",
  "INTERROGATION", "INTERVENTION", "JUDGMENT", "LOGICAL", "OBJECTION", "PARADOX", "PERSPECTIVE", "PREJUDICE",
  "PROPOSITION", "RATIONALE", "REASONING", "REFUTATION", "RELEVANCE", "RIGOR", "SCRUTINY", "VERIFICATION",

  // EXECUTIVE FUNCTION & STUDY STRATEGIES (35)
  "ACCOUNTABILITY", "ADAPTABILITY", "AGENDA", "ATTENTION", "BRAINSTORM", "CALENDAR", "CONCENTRATION", "CONSISTENCY",
  "DEADLINE", "DISCIPLINE", "EVALUATE", "FLEXIBILITY", "FOCUS", "GOAL", "HABIT", "INITIATIVE",
  "MANAGEMENT", "MINDSET", "MONITORING", "OBJECTIVE", "ORGANIZATION", "PACING", "PLANNING", "PRACTICE",
  "PREPARATION", "PRIORITIZE", "PROCEDURE", "PRODUCTIVITY", "PROGRESS", "REVIEW", "ROUTINE", "SCHEDULE",
  "SELF-REGULATION", "STRATEGY", "TIMING", "TRACKING", "VISUALIZATION",

  // ARTS, CULTURE & CREATIVE METHODOLOGIES (23)
  "ACRYLIC", "AESTHETIC", "CHOREOGRAPHY", "COLLAGE", "COMPOSITION", "CURATOR", "DESIGN", "EXPRESSION",
  "FILM", "FORM", "HARMONY", "IMPROVISATION", "MEDIUM", "MOVEMENT", "MURAL", "PALETTE",
  "PERSPECTIVE", "PORTRAIT", "REPERTOIRE", "SCULPTURE", "SYMPHONY", "TEXTURE", "VISION"
];

const dictClass4 = [

  "ABOUT", "ABOVE", "ACCEPT", "ACROSS", "AFTER", "AGAIN", "AGAINST", "ALMOST",
  "ALONG", "ALREADY", "ALWAYS", "AMONG", "ANIMAL", "ANOTHER", "ANSWER", "ANY",
  "ANYONE", "ANYTHING", "APPEAR", "APPROACH", "AROUND", "ARRIVE", "ARTICLE",
  "AS", "ASK", "AT", "ATTACK", "AUGUST", "AUNT", "AWAKE", "BABY", "BACK",
  "BACKGROUND", "BAD", "BAG", "BAKE", "BALL", "BAND", "BANK", "BAR", "BASE",
  "BASKET", "BATH", "BATTLE", "BE", "BEACH", "BEAR", "BEAT", "BEAUTIFUL",
  "BECAUSE", "BECOME", "BED", "BEDROOM", "BEEN", "BEFORE", "BEGAN", "BEGIN",
  "BEHIND", "BELIEVE", "BELL", "BELONG", "BELOW", "BESIDE", "BEST", "BETTER",
  "BETWEEN", "BEYOND", "BICYCLE", "BIG", "BILL", "BIRD", "BIRTH", "BIRTHDAY",
  "BIT", "BLACK", "BLOOD", "BLOW", "BLUE", "BOARD", "BOAT", "BODY", "BONE",
  "BOOK", "BORDER", "BORN", "BOTH", "BOTTLE", "BOTTOM", "BOX", "BOY", "BRAIN",
  "BRANCH", "BREAD", "BREAK", "BREAKFAST", "BREATH", "BRIDGE", "BRIGHT",
  "BRING", "BROAD", "BROKEN", "BROTHER", "BROWN", "BUILD", "BUILDING", "BURN",
  "BUT", "BUTTER", "BUTTON", "BUY", "BY", "CABIN", "CAGE", "CAKE", "CALL",
  "CALM", "CAME", "CAMP", "CAN", "CANDLE", "CANDY", "CAP", "CAPTAIN", "CAR",
  "CARD", "CARE", "CAREFUL", "CAREFULLY", "CARRIED", "CARRY", "CASE", "CAST",
  "CASTLE", "CAT", "CATCH", "CAUSE", "CAVE", "CELL", "CENT", "CENTER", "CENTURY",
  "CERTAIN", "CHAIN", "CHAIR", "CHALK", "CHANGE", "CHAPTER", "CHARACTER",
  "CHARGE", "CHART", "CHECK", "CHEESE", "CHICKEN", "CHILD", "CHILDREN", "CHIMNEY",
  "CHINA", "CHIP", "CHOCOLATE", "CHOOSE", "CHRISTMAS", "CHURCH", "CIRCLE", "CITY",
  "CLAP", "CLASS", "CLASSROOM", "CLEAN", "CLEAR", "CLIMB", "CLOCK", "CLOSE",
  "CLOTHES", "CLOUD", "CLOUDY", "CLUB", "COACH", "COAL", "COAST", "COAT", "COFFEE",
  "COLD", "COLLECT", "COLLEGE", "COLOR", "COME", "COMFORTABLE", "COMMON",
  "COMPANY", "COMPARE", "COMPLETE", "COMPUTER", "CONCERT", "CONDITION", "CONNECT",
  "CONSIDER", "CONSIST", "CONTAIN", "CONTINUE", "CONTROL", "CONVERSATION", "COOK",
  "COOKIE", "COOL", "COPPER", "COPY", "CORNER", "COTTON", "COULD", "COUNT",
  "COUNTRY", "COURSE", "COURT", "COUSIN", "COVER", "COW", "CRACK", "CRAFT",
  "CRASH", "CRAWL", "CRAZY", "CREATE", "CREATURE", "CREEK", "CREW", "CRICKET",
  "CROSS", "CROWD", "CRY", "CUP", "CUPBOARD", "CURIOUS", "CURRENT", "CURTAIN",
  "CURVE", "CUSHION", "CUT", "CYCLE", "DAILY", "DAMAGE", "DANCE", "DANGER",
  "DANGEROUS", "DARK", "DATE", "DAUGHTER", "DAY", "DEAD", "DEAL", "DEAR", "DEATH",
  "DECEMBER", "DECIDE", "DECISION", "DEEP", "DEER", "DEFEND", "DEGREE", "DELAY",
  "DELIGHT", "DELIVER", "DEMAND", "DEMONSTRATE", "DEN", "DENTIST", "DEPEND",
  "DESCRIBE", "DESERT", "DESIGN", "DESK", "DESTROY", "DETAIL", "DETERMINE",
  "DEVELOP", "DIAMOND", "DIARY", "DICE", "DID", "DIE", "DIFFERENCE", "DIFFERENT",
  "DIFFICULT", "DIG", "DINNER", "DIRECT", "DIRECTION", "DIRT", "DISAPPEAR",
  "DISCOVER", "DISCUSS", "DISEASE", "DISH", "DISTANCE", "DISTRIBUTE", "DIVIDE",
  "DO", "DOCTOR", "DOG", "DOLL", "DOLLAR", "DOOR", "DOT", "DOUBLE", "DOUBT",
  "DOWN", "DOZEN", "DRAW", "DREAM", "DRESS", "DRINK", "DRIVE", "DROP", "DROVE",
  "DRY", "DUCK", "DUE", "DULL", "DURING", "DUST", "DUTY", "EACH", "EAGER", "EAR",
  "EARLY", "EARN", "EARTH", "EASE", "EAST", "EASY", "EAT", "EDGE", "EDUCATION",
  "EFFECT", "EFFORT", "EGG", "EIGHT", "EITHER", "ELBOW", "ELECTRIC", "ELEMENT",
  "ELEPHANT", "ELSE", "EMPTY", "ENCOURAGE", "END", "ENEMY", "ENERGY", "ENGINE",
  "ENGINEER", "ENJOY", "ENOUGH", "ENTER", "ENTIRE", "ENTRANCE", "ENVELOPE",
  "EQUAL", "EQUIPMENT", "ESCAPE", "ESPECIALLY", "ESTABLISH", "EVEN", "EVENING",
  "EVENT", "EVER", "EVERY", "EVERYBODY", "EVERYONE", "EVERYTHING", "EXACT",
  "EXAM", "EXAMPLE", "EXCELLENT", "EXCEPT", "EXCITE", "EXCITED", "EXCITING",
  "EXCUSE", "EXERCISE", "EXPECT", "EXPERIENCE", "EXPERIMENT", "EXPLAIN",
  "EXPLORE", "EXPRESS", "EXTRA", "EYE", "EYEBROW", "EYELASH", "EYELID", "FACE",
  "FACT", "FACTORY", "FAIL", "FAIR", "FAIRY", "FAITH", "FALL", "FAMILY", "FAMOUS",
  "FAN", "FANCY", "FAR", "FARM", "FARMER", "FAST", "FAT", "FATHER", "FAVORITE",
  "FEAR", "FEATHER", "FEBRUARY", "FED", "FEED", "FEEL", "FEET", "FELL", "FELLOW",
  "FELT", "FENCE", "FERRET", "FERRY", "FEW", "FIELD", "FIFTEEN", "FIFTH", "FIFTY",
  "FIGHT", "FIGURE", "FILE", "FILL", "FILM", "FINAL", "FIND", "FINE", "FINGER",
  "FINISH", "FIRE", "FIRST", "FISH", "FIST", "FIT", "FIVE", "FIX", "FLAG",
  "FLAME", "FLAT", "FLEA", "FLED", "FLEW", "FLIGHT", "FLIP", "FLOAT", "FLOCK",
  "FLOOR", "FLOWER", "FLY", "FOG", "FOLD", "FOLLOW", "FOOD", "FOOL", "FOOT",
  "FOOTBALL", "FOR", "FORCE", "FOREST", "FORGET", "FORGOT", "FORK", "FORM",
  "FORMER", "FORT", "FORTY", "FORWARD", "FOUND", "FOUR", "FOURTEEN", "FOURTH",
  "FOX", "FRAME", "FREE", "FREEDOM", "FREEZE", "FRESH", "FRIEND", "FRIENDLY",
  "FRIENDSHIP", "FRIGHTEN", "FROG", "FROM", "FRONT", "FROST", "FROZEN", "FRUIT",
  "FULL", "FUN", "FUNCTION", "FUND", "FUNNY", "FUR", "FURNITURE", "FURTHER",
  "FUTURE", "GAME", "GARDEN", "GAS", "GATE", "GATHER", "GAVE", "GENERAL",
  "GENTLE", "GENTLEMAN", "GET", "GIFT", "GIRL", "GIVE", "GLAD", "GLASS", "GLOBE",
  "GO", "GOAL", "GOAT", "GOD", "GOLD", "GOLDEN", "GOOD", "GOODBYE", "GOOSE",
  "GOVERNMENT", "GRAB", "GRADE", "GRAIN", "GRAMMAR", "GRAND", "GRANDFATHER",
  "GRANDMOTHER", "GRASS", "GRATEFUL", "GRAY", "GREAT", "GREEN", "GREET", "GREW",
  "GROUND", "GROUP", "GROW", "GROWN", "GUARD", "GUESS", "GUEST", "GUIDE", "GULF",
  "GUN", "GUY", "GYM", "HELLO", "HOUSE", "INSIDE", "KITCHEN", "LITTLE", "LUNCH",
  "MARKET", "MORNING", "MOTHER", "NUMBER", "ORANGE", "PEOPLE", "PENCIL", "PLEASE",
  "POCKET", "PURPLE", "RABBIT", "SCHOOL", "SISTER", "SLEEP", "SMILE", "SQUARE",
  "STREET", "SUMMER", "TABLE", "THINGS", "TODAY", "UNDER", "WATER", "WHEEL",
  "WINDOW", "WINTER", "YELLOW", "YESTERDAY", "YOUNG", "ZEBRA",

  // 1. ADVANCED ACADEMIC & CONCEPTUAL FOUNDATIONS (50)
  "ABSTRACTION", "ACCURACY", "AGRICULTURE", "ALLEGIANCE", "AMENDMENT", "ANTHROPOLOGY", "ARCHITECTURE", "ARCHIVE", "ASSERTION", "AUTONOMY",
  "BENEVOLENCE", "BREAKTHROUGH", "BUREAUCRACY", "CENSUS", "CHRONICLE", "CITATION", "COALITION", "COMMERCE", "CONSTITUTION", "CONTROVERSY",
  "CORROBORATION", "CULMINATION", "DEMOCRACY", "DERIVATION", "DIAGNOSIS", "DIMENSION", "DISCIPLINE", "DOCUMENTATION", "DYNAMICS", "EMANCIPATION",
  "EMPIRICAL", "ENCLOSURE", "EQUITY", "EXEMPLIFICATION", "FACILITATION", "FEDERATION", "FRAGMENTATION", "GENEALOGY", "GOVERNANCE", "HERITAGE",
  "HYPOTHETICAL", "IDEOLOGY", "IMPLICATION", "INFRASTRUCTURE", "JURISPRUDENCE", "KINETICS", "LEGISLATIVE", "MAGNITUDE", "NARRATOLOGY", "NOMENCLATURE",

  // 2. COGNITIVE & RESEARCH VERBS (40)
  "ACCUMULATE", "ADVOCATE", "APPRAISE", "ASCERTAIN", "ASSESS", "CALIBRATE", "CATEGORIZE", "CLARIFY", "COMPILE", "COMPREHEND",
  "CONSOLIDATE", "CORRELATE", "CRITIQUE", "DECOMPOSE", "DELINEATE", "DERIVE", "DISSECT", "ELUCIDATE", "EMPHASIZE", "ENHANCE",
  "EVALUATE", "EXTRACT", "FORMULATE", "INTEGRATE", "INVESTIGATE", "MODIFY", "NAVIGATE", "OPTIMIZE", "PREDICT", "SYNTHESIZE",
  "VALIDATE", "VERIFY", "VISUALIZE", "ALIGN", "COMPUTE", "CONSTRUCT", "WEIGH", "CALCULATE", "CONCEIVE", "REFINE",

  // 3. COMPLEX DESCRIPTORS & ACADEMIC MODIFIERS (40)
  "ABUNDANT", "ACCLAIMED", "ACUMEN", "ADAPTIVE", "ALTRUISTIC", "ANTHROPOGENIC", "ARDUOUS", "AUTHENTIC", "CAPACIOUS", "COGNITIVE",
  "COMPREHENSIVE", "CONSEQUENTIAL", "CONTINGENT", "CONVERGENT", "DEDUCTIVE", "DELETERIOUS", "DIMINISHING", "DIVERSE", "DYNAMIC", "EMPIRICAL",
  "EXPONENTIAL", "FUNCTIONAL", "HETEROGENEOUS", "IMPLICIT", "INCLUSIVE", "INDICATIVE", "INHERENT", "INTERMEDIATE", "LEXICAL", "MARGINAL",
  "MECHANISTIC", "MITIGATING", "OBJECTIVE", "OPTIMAL", "PARADOXICAL", "PERSUASIVE", "PRECISION", "PROVISIONAL", "SYSTEMATIC", "TANGIBLE",

  // 4. ADVANCED MATHEMATICS & DATA REASONING (45)
  "ABSCISSA", "ALGEBRAIC", "APPROXIMATION", "ARITHMETIC", "ASCENDING", "BINOMIAL", "CARTESIAN", "CIRCUMFERENCE", "COEFFICIENT", "CONGRUENT",
  "CONSTANT", "COORDINATES", "CORRELATION", "DECIMAL", "DENOMINATOR", "DERIVATIVE", "DIAMETER", "DISCRETE", "DIVISOR", "EQUATION",
  "EQUIVALENT", "ESTIMATION", "EXPONENT", "FACTORIAL", "FRACTION", "GEOMETRIC", "HISTOGRAM", "HYPOTENUSE", "INTEGER", "INTERVAL",
  "ISOSCELES", "MEAN", "MEDIAN", "MODE", "MULTIPLIER", "NUMERATOR", "ORDINATE", "PERPENDICULAR", "POLYGON", "PROBABILITY",
  "QUOTIENT", "RADIUS", "RATIO", "REMAINDER", "VARIABLE",

  // 5. LIFE, EARTH & PHYSICAL SCIENCES (45)
  "ABSORPTION", "ACCELERATION", "AEROBIC", "ANATOMY", "ANTIBODIES", "ASYMMETRY", "BIOMASS", "BIOME", "CAPILLARY", "CARBOHYDRATE",
  "CELLULAR", "CHEMICAL", "CIRCULATORY", "CLASSIFICATION", "COMBUSTION", "CONDENSATION", "CONDUCTOR", "CONSERVATION", "CONVECTION", "DENSITY",
  "DIFFUSION", "ELECTRICITY", "ENZYME", "EVOLUTION", "FILTRATION", "GENETICS", "GERMINATION", "HORMONE", "INVERTEBRATE", "MAGNETISM",
  "METABOLISM", "MUSCLE", "NERVE", "ORGAN", "PHOTOSYNTHESIS", "PROTEIN", "RESPIRATION", "SKELETON", "SYNAPSE", "TISSUE",
  "VACCINE", "VERTEBRATE", "VIRUS", "WAVELENGTH", "ZOOLOGY",

  // 6. HISTORY, CIVICS & GLOBAL SYSTEMS (45)
  "ALLIANCE", "BALANCE", "CAPITAL", "COLONIALISM", "CURRENCY", "DEFICIT", "DELEGATE", "DIPLOMACY", "ECONOMICS", "ELECTION",
  "EMIGRATION", "EXPENDITURE", "EXPORT", "FEDERATION", "INFLATION", "JUDICIARY", "LEGISLATION", "MARKET", "MIGRATION", "MONOPOLY",
  "NATIONALISM", "PARLIAMENT", "POLICY", "PRODUCTION", "PROFIT", "PROPOSAL", "PROVIDER", "REFERENDUM", "REGULATION", "REPRESENTATION",
  "RESOURCE", "REVENUE", "SANCTION", "SOVEREIGNTY", "SUPPLY", "TARIFF", "TAXATION", "TREATY", "UNION", "VERIFICATION",
  "VOTING", "WEALTH", "YIELD", "ZONING", "ACQUISITION",

  // 7. LANGUAGE ARTS, COMPOSITION & LITERARY ANALYSIS (45)
  "ABRIDGED", "ALLITERATION", "AMBIGUITY", "ANTAGONIST", "ANTITHESIS", "APEX", "ARGUMENTATIVE", "ASSESSMENT", "CENSUS", "CLAUSE",
  "CLIMAX", "CONNOTATION", "CONTEXTUAL", "DEBATE", "DENOTATION", "DESCRIPTIVE", "DIAGRAM", "DIALECT", "DIALOGUE", "DRAFT",
  "EDITING", "ELABORATION", "EPILOGUE", "EVIDENCE", "EXCERPT", "EXPOSITION", "FIGURATIVE", "FORESIGHT", "GENRE", "IDIOM",
  "IMAGERY", "INFERENCE", "INTERPRETATION", "INTRODUCTORY", "LITERARY", "MANUSCRIPT", "METAPHOR", "NARRATOR", "ONTOLOGY", "OUTLINE",
  "PARAPHRASE", "PERSUASIVE", "PLOT", "POETRY", "PRONOUN",

  // 8. TECHNOLOGY, CODING & DIGITAL LITERACY (40)
  "ALGORITHM", "APPLICATION", "ARCHITECTURE", "AUTOMATION", "BANDWIDTH", "BINARY", "CIRCUIT", "CLOUD", "CODE", "COMPILATION",
  "COMPRESS", "DATABASE", "DEBUG", "DIGITIZE", "DOWNLOAD", "DRONE", "ENCRYPTION", "FIRMWARE", "HARDWARE", "HAPTIC",
  "INTERFACE", "INTERNET", "LATENCY", "MAINFRAME", "NETWORK", "OPTICAL", "PROTOCOL", "ROBOTICS", "SERVER", "SIMULATION",
  "SOFTWARE", "STREAMING", "TELEMETRY", "TERABYTE", "UPLOAD", "VIRTUAL", "WIRED", "WIRELESS", "WORKSTATION", "ZERO-TRUST",

  // 9. HEALTH, PSYCHOLOGY & SOCIAL-EMOTIONAL LEARNING (40)
  "ADOLESCENCE", "ANXIETY", "APPETITE", "BEHAVIOR", "CALCIUM", "CARDIOVASCULAR", "COGNITION", "DEVELOPMENT", "DIET", "DOPAMINE",
  "ENDOCRINE", "EMOTION", "EMPLOYEE", "ENVIRONMENTAL", "EXERCISE", "FEVER", "FLEXIBILITY", "GROWTH", "HEALTH", "HEARING",
  "HORMONES", "IMMUNITY", "INFANCY", "INJURY", "INSULIN", "MENTAL", "METABOLISM", "MOTOR", "NEUROLOGICAL", "NUTRITION",
  "PERCEPTION", "PHYSIOLOGY", "PUBERTY", "RESILIENCE", "RESPIRATORY", "SENSORY", "STRESS", "WELLNESS", "AUTOREGULATION", "EMPATHY",

  // 10. CRITICAL THINKING & LOGICAL REASONING (35)
  "ANALYSIS", "ASSUMPTION", "BIAS", "CAUSALITY", "COHERENCE", "CONJECTURE", "CONSENSUS", "CONTRADICTION", "CRITERIA", "DEDUCTION",
  "DISCOURSE", "DISPUTE", "DISTINCTION", "DOUBT", "EXAMINATION", "FALLACY", "ILLOGICAL", "INDUCTION", "INQUIRY", "INTERROGATION",
  "INTERVENTION", "JUDGMENT", "OBJECTION", "PARADOX", "PREJUDICE", "PROPOSITION", "RATIONALE", "REASONING", "REFUTATION", "RELEVANCE",
  "RIGOR", "SCRUTINY", "VERIFICATION", "EVIDENCE", "LOGIC",

  // 11. EXECUTIVE FUNCTION & RESEARCH SKILLS (35)
  "ACCOUNTABILITY", "AGENDA", "ATTENTION", "BRAINSTORM", "CALENDAR", "CONCENTRATION", "CONSISTENCY", "DEADLINE", "DISCIPLINE", "EVALUATE",
  "FLEXIBILITY", "FOCUS", "GOAL", "HABIT", "INITIATIVE", "MANAGEMENT", "MINDSET", "MONITORING", "OBJECTIVE", "ORGANIZATION",
  "PACING", "PLANNING", "PRACTICE", "PREPARATION", "PRIORITIZE", "PROCEDURE", "PRODUCTIVITY", "PROGRESS", "REVIEW", "ROUTINE",
  "SCHEDULE", "SELF-REGULATION", "STRATEGY", "TIMING", "TRACKING",

  // 12. ARTS, CULTURE & CREATIVE EXPRESSION (35)
  "AESTHETIC", "ANIMATION", "ARCHIVAL", "CINEMATOGRAPHY", "CONSERVATION", "CURATOR", "DESIGN", "EXPRESSION", "FILM", "FORM",
  "HARMONY", "ILLUSTRATION", "IMPROVISATION", "MEDIUM", "MOVEMENT", "MURAL", "ORCHESTRATION", "PALETTE", "PERSPECTIVE", "PORTRAIT",
  "REPERTOIRE", "SCULPTURE", "SYMPHONY", "TEXTURE", "THEATER", "TONALITY", "TYPOGRAPHY", "VISUALIZATION", "VOCAL", "WATERCOLOR",
  "ACROBATICS", "BALLET", "CHOREOGRAPHY", "DRAMA", "EXHIBITION"
];

const dictClass5 = [
  // 1. ADVANCED ACADEMIC & INTERDISCIPLINARY CONCEPTS (40)
  "ABSTRACTION", "AGGREGATION", "APPLICABILITY", "ARCHETYPAL", "AUTONOMY", "BENCHMARK", "CATEGORIZATION", "CHRONOLOGICAL",
  "COMPARATIVE", "COMPLEXITY", "CONCEPTUAL", "CONGRUENCE", "CONTINUUM", "CORRELATIONAL", "CURRICULAR", "DEDUCTIVE",
  "DECONSTRUCTION", "DEMOGRAPHIC", "DICHOTOMY", "DIFFERENTIATION", "DISCIPLINARY", "DIVERGENT", "EMPIRICAL", "EPISTEMOLOGY",
  "EVALUATIVE", "EXEMPLIFICATION", "EXPLORATORY", "FOUNDATIONAL", "HEGEMONY", "HETEROGENEOUS", "HYPOTHETICAL", "INTERDISCIPLINARY",
  "INTERPRETATIVE", "METHODOLOGICAL", "NARRATOLOGY", "NOMENCLATURE", "PARADIGMATIC", "PEDAGOGICAL", "PLURALISTIC", "QUALITATIVE",

  // 2. ANALYTICAL & EVALUATIVE VERBS (45)
  "APPRECIATE", "APPREHEND", "ASSESS", "AUGMENT", "CIRCUMSCRIBE", "COALESCE", "COMPILATE", "CONCEPTUALIZE",
  "CONCRETIZE", "CONSOLIDATE", "CONTEXTUALIZE", "CORRELATE", "CRITIQUE", "DECONSTRUCT", "DELIMIT", "DEMYSTIFY",
  "DISSECT", "DISTINGUISH", "ELABORATE", "EMBARK", "ENCOMPASS", "ENGENDER", "ENUMERATE", "EXTRAPOLATE",
  "FACILITATE", "FORTIFY", "FORMULATE", "FRAGMENT", "GENERATE", "HYPOTHESIZE", "ILLUMINATE", "IMPLICATE",
  "INNOVATE", "INTERROGATE", "JOURNALIZE", "JUSTIFY", "METICULATE", "OPTIMIZE", "ORCHESTRATE", "PREDICATE",
  "QUANTIFY", "RECONFIGURE", "RECONSIDER", "REDEFINE", "SYNTHESIZE", "TRIAGE",

  // 3. COMPLEX ACADEMIC DESCRIPTORS (40)
  "ACCLAIMED", "ACRID", "ADAMANT", "AMBIGUOUS", "ANOMALOUS", "ANTICIPATORY", "ASCETIC", "ASSERTIVE",
  "AUSTERE", "AUTONOMOUS", "BENEVOLENT", "BLATANT", "CADENT", "CANDID", "CAPRICIOUS", "CATASTROPHIC",
  "CHAOTIC", "COGNIZANT", "COHERENT", "COMPATIBLE", "COMPULSIVE", "CONGENIAL", "CONSISTENT", "CONSTRAINED",
  "CONTEMPORARY", "CONTINGENT", "CORROSIVE", "CURSORY", "DEBILITATING", "DECISIVE", "DEMURE", "DIDACTIC",
  "DIMINUTIVE", "DISPARATE", "ECCENTRIC", "EFFICIENT", "EMPATHETIC", "ENIGMATIC", "ERUDITE", "EXPLICIT",

  // 4. ADVANCED MATH & ALGEBRAIC REASONING (45)
  "ABSOLUTE", "ADDEND", "APOTHEM", "ASYMPTOTE", "AXIOM", "CHORD", "COMPOSITE", "CONCENTRIC",
  "COROLLARY", "COSECANT", "COSINE", "COVARIANCE", "DEGREE", "DIFFERENTIAL", "DOMAIN", "EQUILATERAL",
  "EXTREMA", "FUNCTION", "HARMONIC", "HEXAGON", "HYPERBOLA", "IDENTITY", "IMAGINARY", "INCREMENT",
  "INEQUALITY", "INTEGRAL", "INTERCEPT", "IRRATIONAL", "LATERAL", "LIMIT", "LINEAR", "LOGARITHM",
  "MAGNITUDE", "MATRIX", "MAXIMUM", "MINIMUM", "MODULUS", "MONOMIAL", "PARAMETER", "PARABOLA",
  "POLYNOMIAL", "PROGRESSION", "PROPORTION", "QUADRATIC", "QUADRILATERAL",

  // 5. EARTH, ECOLOGY & PHYSICAL SCIENCES (45)
  "ACIDIC", "AEROBIC", "AGGREGATE", "ALGAE", "ALLUVIUM", "AMMONIA", "ANEMOMETER", "AQUATIC",
  "ARID", "BAROMETER", "BASALT", "BIODEGRADABLE", "BOSON", "CARBON", "CATALYTIC", "CELSIUS",
  "CENTRIFUGE", "CHLOROPHYLL", "CLIMATOLOGY", "CONDUCTION", "CONDUIT", "CORAL", "CORIOLIS", "DECOMPOSER",
  "DEFORESTATION", "DENITRIFICATION", "DESALINATION", "DILUTION", "DISSOLVE", "DROUGHT", "DYNAMO", "ELECTROMAGNETIC",
  "EMISSION", "EXOTHERMIC", "EXTINCTION", "FAULT", "FERMENTATION", "FISSION", "FLUORESCENCE", "FUSION",
  "GEOLOGIC", "HELIUM", "HERTZ", "HUMIDITY", "HYDROCARBON",

  // 6. HISTORY, CIVICS & GLOBAL SYSTEMS (40)
  "ABOLITION", "ACCORD", "AGENCY", "ANARCHY", "APPEASEMENT", "ARMISTICE", "AUTOCRACY", "BALLOT",
  "BICAMERAL", "BLOC", "CABINET", "CAMPAIGN", "CAPITALISM", "CARTEL", "CASTE", "CAUCUS",
  "CHARTER", "COMMONWEALTH", "COMPACT", "CONFER", "CONGRESS", "CONSERVATISM", "CONSTITUTIONAL", "CONTINGENT",
  "CONVENTION", "COOPERATIVE", "CORRUPTION", "COUNCIL", "COUP", "DEPENDENCY", "DEPUTY", "DETENTE",
  "DIRECTIVE", "DISENFRANCHISEMENT", "DIVISION", "DOMINION", "ELECTORATE", "EMBARGO", "ENCLOSURE", "ENTENTE",

  // 7. LANGUAGE ARTS, RHETORIC & LITERARY CRAFT (40)
  "ACROSTIC", "ANACHRONISM", "ANTHOLOGY", "ANTIHERO", "APOSTROPHE", "ARCHETYPAL", "ASSONANCE", "AUTOBIOGRAPHY",
  "CADENCE", "CANTO", "CHARACTERIZATION", "COLLOQUIALISM", "CONSONANCE", "CONVENTION", "CRESCENDO", "CRITIC",
  "ELEGY", "ELLIPSIS", "ENCOMIUM", "EPIGRAM", "EPITAPH", "ESSAY", "EUPHEMISM", "EUPHONY",
  "EXEGESIS", "FABULA", "FOLKLORE", "FOIL", "FOOTNOTE", "GLOSSARY", "HYPERBOLE", "IAMBIC",
  "INSCRIPTION", "IRONY", "LAMENT", "LIBRETTO", "LYRIC", "MEMOIR", "MONOLOGUE", "MOTIF",

  // 8. TECHNOLOGY, CODING & DIGITAL CITIZENSHIP (35)
  "ACCESS", "AGGREGATION", "ANALYTICS", "API", "ARTIFICIAL", "BACKUP", "BIOMETRIC", "BLOB",
  "BYTE", "CACHING", "CLUSTER", "COMPILE", "CONFIGURATION", "CONNECTIVITY", "CONTAINER", "CRAWL",
  "CREDENTIALS", "CRYPTOGRAPHY", "CYBERSECURITY", "DEPLOYMENT", "DIRECT", "DISK", "DOWNTIME", "EMBED",
  "ENCODING", "ENDPOINT", "ENGINE", "ENTERPRISE", "ETHERNET", "EXCHANGE", "EXECUTE", "EXPLOIT",
  "EXTENSION", "FABRIC", "FIREWALL",

  // 9. HEALTH, PSYCHOLOGY & SOCIAL-EMOTIONAL LEARNING (35)
  "ADOLESCENCE", "ADVISORY", "AFFECT", "AFFINITY", "AGGRESSION", "AMYGDALA", "ANOREXIA", "ANTICIPATION",
  "AROUSAL", "ASSERTIVE", "ATTACHMENT", "AUTISM", "AUTOREGULATION", "AVERSION", "AWARENESS", "BENEFIT",
  "BIPOLAR", "BOUNDARY", "BURNOUT", "CALIBRATION", "CASEWORK", "CATHARSIS", "COACHING", "COHESION",
  "COLLABORATIVE", "COMPREHENSION", "CONDITIONING", "CONFIDENCE", "CONSCIOUSNESS", "CONSOLIDATION", "CONTAGION", "COUNSELING",
  "CRISIS", "CRUCIAL", "CULTURE",

  // 10. CRITICAL THINKING & RESEARCH METHODOLOGY (35)
  "APPRAISAL", "ARGUMENTATION", "CORROBORATION", "CRITICALITY", "DECONSTRUCTIVE", "DEMOGRAPHIC", "DEDUCTIVE", "DISCERNMENT",
  "EPISTEMIC", "EVALUATIVE", "EXEMPLIFICATION", "EXPLORATORY", "FOUNDATIONAL", "HEURISTIC", "INDUCTIVE", "INFERENCE",
  "INTERPRETIVE", "INVESTIGATIVE", "LOGICAL", "METACOGNITIVE", "METHODOLOGICAL", "OBJECTION", "PARADIGMATIC", "PERSPECTIVAL",
  "PROPOSITIONAL", "QUALITATIVE", "QUANTITATIVE", "RATIONALITY", "REFLECTIVE", "REASONING", "RELEVANCY", "RIGOROUS",
  "SCIENTIFIC", "SYSTEMATIC", "VALIDATION",

  // 11. EXECUTIVE FUNCTION & PROJECT MANAGEMENT (35)
  "ADAPTABILITY", "ALLOCATION", "ANTICIPATION", "ASSESSMENT", "AUTONOMY", "BREAKDOWN", "CHECKLIST", "COLLABORATION",
  "COMMUNICATION", "DELEGATION", "DELIVERY", "DOCUMENTATION", "EFFICIENCY", "FEEDBACK", "FRAMEWORK", "IMPLEMENTATION",
  "ITERATION", "LIAISON", "MILESTONE", "MITIGATION", "NEGOTIATION", "OPTIMIZATION", "OVERSIGHT", "PARAMETER",
  "PROCEDURE", "PROTOCOL", "REALLOCATION", "REFINEMENT", "SCALABILITY", "SCHEDULING", "STREAMLINING", "SYNCHRONIZATION",
  "TASKING", "TIMELINE", "WORKFLOW",

  // 12. ARTS, MEDIA & CULTURAL STUDIES (35)
  "AESTHETICS", "ANIMATION", "ARCHIVAL", "CINEMATOGRAPHY", "CONSERVATION", "CURATOR", "DESIGN", "EXPRESSION",
  "FILM", "FORM", "HARMONY", "ILLUSTRATION", "IMPROVISATION", "MEDIUM", "MOVEMENT", "MURAL",
  "ORCHESTRATION", "PALETTE", "PERSPECTIVE", "PORTRAIT", "REPERTOIRE", "SCULPTURE", "SYMPHONY", "TEXTURE",
  "THEATER", "TRADITION", "VISUAL", "AESTHETIC", "CHOREOGRAPHY", "CRAFTSMANSHIP", "COMPOSITION", "CONTEMPORARY",
  "DIGITAL", "EXHIBITION", "GALLERY"
];

const dictClass6 = [
  "ABANDON", "ABILITY", "ABLE", "ABNORMAL", "ABOVE", "ABROAD", "ABSENCE", "ABSOLUTE",
  "ABSORB", "ABSTRACT", "ABUNDANT", "ACADEMIC", "ACCEPT", "ACCESS", "ACCIDENT",
  "ACCOMPANY", "ACCOMPLISH", "ACCORDING", "ACCOUNT", "ACCURATE", "ACCUSE", "ACHIEVE",
  "ACID", "ACKNOWLEDGE", "ACQUAINT", "ACQUIRE", "ACROSS", "ACT", "ACTION", "ACTIVE",
  "ACTIVITY", "ACTOR", "ACTRESS", "ACTUAL", "ADAPT", "ADD", "ADDITION", "ADDRESS",
  "ADEQUATE", "ADJUST", "ADMINISTRATION", "ADMIRE", "ADMIT", "ADOPT", "ADULT",
  "ADVANCE", "ADVANTAGE", "ADVENTURE", "ADVERTISE", "ADVICE", "ADVISE", "ADVOCATE",
  "AERIAL", "AFFECT", "AFFECTION", "AFFORD", "AFRAID", "AFTER", "AFTERNOON",
  "AFTERWARD", "AGAIN", "AGAINST", "AGE", "AGENCY", "AGENT", "AGREE", "AGREEMENT",
  "AGRICULTURE", "AHEAD", "AID", "AIM", "AIR", "AIRCRAFT", "AIRLINE", "AIRPORT",
  "ALARM", "ALBUM", "ALCOHOL", "ALERT", "ALGEBRA", "ALIKE", "ALIVE", "ALL", "ALLOW",
  "ALMOST", "ALONE", "ALONG", "ALREADY", "ALSO", "ALTER", "ALTERNATE", "ALTHOUGH",
  "ALTOGETHER", "ALUMINUM", "ALWAYS", "AMATEUR", "AMAZING", "AMBITION", "AMBULANCE",
  "AMONG", "AMOUNT", "AMPLE", "AMUSE", "ANALYSIS", "ANALYZE", "ANCIENT", "ANGER",
  "ANGLE", "ANGRY", "ANIMAL", "ANKLE", "ANNOUNCE", "ANNOY", "ANNUAL", "ANOTHER",
  "ANSWER", "ANTICIPATE", "ANXIETY", "ANXIOUS", "ANY", "ANYBODY", "ANYMORE",
  "ANYONE", "ANYTHING", "ANYWAY", "ANYWHERE", "APART", "APARTMENT", "APOLOGIZE",
  "APPARATUS", "APPARENT", "APPEAL", "APPEAR", "APPEARANCE", "APPLIANCE", "APPLY",
  "APPOINT", "APPROACH", "APPROPRIATE", "APPROVE", "APPROXIMATE", "ARCH", "ARCHITECT",
  "AREA", "ARGUE", "ARGUMENT", "ARISE", "ARM", "ARMY", "AROUND", "ARRANGE",
  "ARRANGEMENT", "ARREST", "ARRIVAL", "ARRIVE", "ART", "ARTICLE", "ARTIST",
  "ARTISTIC", "AS", "ASH", "ASHAMED", "ASIDE", "ASK", "ASLEEP", "ASPECT", "ASSEMBLE",
  "ASSEMBLY", "ASSERT", "ASSESS", "ASSET", "ASSIGN", "ASSIGNMENT", "ASSIST",
  "ASSISTANCE", "ASSISTANT", "ASSOCIATE", "ASSOCIATION", "ASSUME", "ASSUMPTION",
  "ASSURE", "ASTONISH", "ATHLETE", "ATHLETIC", "ATMOSPHERE", "ATOM", "ATTACH",
  "ATTACK", "ATTAIN", "ATTEMPT", "ATTEND", "ATTENTION", "ATTITUDE", "ATTRACT",
  "ATTRACTIVE", "ATTRIBUTE", "AUBURN", "AUCTION", "AUDIENCE", "AUDIO", "AUDIT",
  "AUGUST", "AUNT", "AUTHOR", "AUTHORITY", "AUTO", "AUTOMATIC", "AUTUMN",
  "AVAILABLE", "AVENUE", "AVERAGE", "AVOID", "AWAKE", "AWARD", "AWARE", "AWAY",
  "AWFUL", "AWKWARD", "AXE", "BABY", "BACHELOR", "BACK", "BACKGROUND", "BACKWARD",
  "BACON", "BADGE", "BADLY", "BAG", "BAKE", "BAKERY", "BALANCE", "BALL", "BALLOON",
  "BAN", "BANANA", "BAND", "BANDAGE", "BANK", "BAR", "BARE", "BARELY",
  "BARGAIN", "BARK", "BARN", "BARREL", "BARRIER", "BASE", "BASEBALL", "BASIC",
  "BASIN", "BASIS", "BASKET", "BASKETBALL", "BAT", "BATH", "BATHE", "BATHROOM",
  "BATTERY", "BATTLE", "BAY", "BE", "BEACH", "BEAM", "BEAN", "BEAR", "BEARD",
  "BEAST", "BEAT", "BEAUTIFUL", "BEAUTY", "BECAUSE", "BECOME", "BED", "BEDROOM",
  "BEE", "BEEF", "BEEN", "BEER", "BEFORE", "BEG", "BEGAN", "BEGIN", "BEGINNER",
  "BEGINNING", "BEHAVE", "BEHAVIOR", "BEHIND", "BEING", "BELIEF", "BELIEVE",
  "BELL", "BELONG", "BELOW", "BELT", "BENCH", "BEND", "BENEATH", "BENEFIT", "BENT",
  "BESIDE", "BEST", "BET", "BETTER", "BETWEEN", "BEYOND", "BICYCLE", "BIG", "BILL",
  "BILLION", "BIND", "BIOLOGY", "BIRD", "BIRTH", "BIRTHDAY", "BIT", "BITE",
  "BITTER", "BLACK", "BLADE", "BLAME", "BLANK", "BLANKET", "BLAST", "BLEED",
  "BLEND", "BLESS", "BLIND", "BLOCK", "BLOOD", "BLOOM", "BLOSSOM", "BLOW", "BLUE",
  "BOARD", "BOAST", "BOAT", "BODY", "BOIL", "BOLD", "BOLT", "BOMB", "BOND", "BONE",
  "BOOK", "BOOT", "BORDER", "BORE", "BORN", "BORROW", "BOSS", "BOTH", "BOTTLE",
  "BOTTOM", "BOUGHT", "BOUNCE", "BOUND", "BOUNDARY", "BOWL", "BOX", "BOY", "BRACE",
  "BRACELET", "BRAIN", "BRANCH", "BRAND", "BRASS", "BRAVE", "BREAD", "BREAK",
  "BREAKFAST", "BREATH", "BREATHE", "BREED", "BRICK", "BRIDGE", "BRIEF", "BRIGHT",
  "BRING", "BROAD", "BROADCAST", "BROKEN", "BRONZE", "BROOCH", "BROOM", "BROTHER",
  "BROWN", "BRUSH", "BUCKET", "BUD", "BUDGET", "BUFFALO", "BUFFER", "BUG", "BUILD",
  "BUILDING", "BULB", "BULK", "BULL", "BULLET", "BUMP", "BUNDLE", "BUNNY",
  "BURDEN", "BUREAU", "BURN", "BURST", "BURY", "BUS", "BUSH", "BUSINESS", "BUSY",
  "BUT", "BUTCHER", "BUTTER", "BUTTERFLY", "BUTTON", "BUY", "BUZZ", "BY", "CAB",
  "CABIN", "CABINET", "CABLE", "CAGE", "CAKE", "CALCULATE", "CALENDAR", "CALL",
  "CALM", "CAME", "CAMEL", "CAMERA", "CAMP", "CAMPAIGN", "CAN", "CANAL", "CANCEL",
  "CANDIDATE", "CANDLE", "CANDY", "CANE", "CANNON", "CANOE", "CANTEEN", "CAP",
  "CAPABLE", "CAPACITY", "CAPITAL", "CAPTAIN", "CAPTURE", "CAR", "CARBON", "CARD",
  "CARE", "CAREFUL", "CARELESS", "CARGO", "CARPET", "CARRIAGE", "CARRIER", "CARRY",
  "CART", "CARVE", "CASE", "CASH", "CASKET", "CAST", "CASTLE", "CASUAL", "CAT",
  "CATCH", "CATEGORY", "CATTLE", "CAUGHT", "CAUSE", "CAUTION", "CAUTIOUS", "CAVE",
  "CEILING", "CELEBRATE", "CELL", "CELLAR", "CEMENT", "CENT", "CENTER", "CENTURAL",
  "CENTURY", "CEREMONY", "CERTAIN", "CERTAINLY", "CERTIFICATE", "CHAIN", "CHAIR",
  "CHAIRMAN", "CHALK", "CHALLENGE", "CHAMPION", "CHANCE", "CHANGE", "CHANNEL",
  "CHAPTER", "CHARACTER", "CHARACTERISTIC", "CHARGE", "CHARM", "CHART", "CHASE",
  "CHEAP", "CHECK", "CHEEK", "CHEER", "CHEERFUL", "CHEESE", "CHEMICAL", "CHEMISTRY",
  "CHERRY", "CHEST", "CHEW", "CHICK", "CHICKEN", "CHIEF", "CHILD", "CHILDHOOD",
  "CHILDREN", "CHILL", "CHIMNEY", "CHIN", "CHINA", "CHIP", "CHOCOLATE", "CHOICE",
  "CHOOSE", "CHOP", "CHORUS", "CHOSE", "CHOSEN", "CHRISTIAN", "CHRISTMAS",
  "CHURCH", "CIGAR", "CIGARETTE", "CIRCLE", "CIRCUMSTANCE", "CIRCUS", "CITIZEN",
  "CITY", "CIVIL", "CLAIM", "CLAP", "CLARIFY", "CLASH", "CLASS", "CLASSIC",
  "CLASSIFICATION", "CLASSIFY", "CLASSROOM", "CLAY", "CLEAN", "CLEAR", "CLEARLY",
  "CLERK", "CLEVER", "CLICK", "CLIENT", "CLIFF", "CLIMB", "CLINIC", "CLIP", "CLOCK",
  "CLOSE", "CLOSELY", "CLOSET", "CLOTH", "CLOTHE", "CLOTHES", "CLOTHING", "CLOUD",
  "CLOUDY", "CLUB", "CLUE", "CLUMP", "CLUSTER", "CLUTCH", "COACH", "COAL", "COARSE",
  "COAST", "COAT", "COBWEB", "COCK", "COCKROACH", "COCOA", "COCONUT", "CODE",
  "COFFEE", "COIL", "COIN", "COLD", "COLLAR", "COLLECT", "COLLECTION", "COLLEGE",
  "COLLISION", "COLOR", "COLORED", "COLUMN", "COMB", "COMBINE", "COME", "COMFORT",
  "COMFORTABLE", "COMMAND", "COMMENT", "COMMERCE", "COMMERCIAL", "COMMIT",
  "COMMITTEE", "COMMON", "COMMUNICATE", "COMMUNICATION", "COMMUNITY", "COMPANY",
  "COMPARE", "COMPARISON", "COMPETE", "COMPETITION", "COMPETITIVE", "COMPETITOR",
  "COMPLAIN", "COMPLAINT", "COMPLETE", "COMPLEX", "COMPLICATE", "COMPONENT",
  "COMPOSE", "COMPOSITION", "COMPOUND", "COMPREHEND", "COMPREHENSION", "COMPRESS",
  "COMPRISE", "COMPUTE", "COMPUTER", "COMRADE", "CONCEAL", "CONCEDE", "CONCEIVE",
  "CONCENTRATE", "CONCENTRATION", "CONCEPT", "CONCERN", "CONCERNING", "CONCERT",
  "CONCLUDE", "CONCLUSION", "CONCRETE", "CONDENSE", "CONDITION", "CONDUCT",
  "CONDUCTOR", "CONFERENCE", "CONFESS", "CONFIDENCE", "CONFIDENT", "CONFINE",
  "CONFIRM", "CONFLICT", "CONFORM", "CONFRONT", "CONFUSE", "CONFUSION",
  "CONGRATULATE", "CONNECT", "CONNECTION", "CONQUER", "CONSCIENCE", "CONSCIOUS",
  "CONSENT", "CONSEQUENCE", "CONSERVE", "CONSIDER", "CONSIDERABLE", "CONSIDERATE",
  "CONSIDERATION", "CONSIST", "CONSISTENT", "CONSOLE", "CONSOLIDATE", "CONSPIRE",
  "CONSTANT", "CONSTITUTE", "CONSTITUTION", "CONSTRUCT", "CONSTRUCTION",
  "CONSULT", "CONSUME", "CONSUMER", "CONSUMPTION", "CONTACT", "CONTAIN",
  "CONTAINER", "CONTEMPORARY", "CONTENT", "CONTENTS", "CONTINUE", "CONTINUED",
  "CONTINUAL", "CONTINUALLY", "CONTINUANCE", "CONTINUATION", "CONTINUOUS",
  "CONTINUOUSLY", "CONTRACT", "CONTRADICT", "CONTRARY", "CONTRAST", "CONTRIBUTE",
  "CONTRIBUTION", "CONTROL", "CONTROVERSIAL", "CONTROVERSY", "CONVENIENCE",
  "CONVENIENT", "CONVENTION", "CONVERSATION", "CONVERSE", "CONVERT", "CONVEY",
  "CONVINCE", "COOK", "COOKIE", "COOL", "COOPERATE", "COORDINATE", "COP", "COPE",
  "COPPER", "COPY", "CORAL", "CORD", "CORE", "CORK", "CORN", "CORNER",
  "CORPORATION", "CORRECT", "CORRECTION", "CORRELATE", "CORRESPOND", "CORRUPT",
  "COST", "COTTON", "COUGH", "COULD", "COUNCIL", "COUNSEL", "COUNT", "COUNTER",
  "COUNTRY", "COUNTY", "COURSE", "COURT", "COUSIN", "COVER", "COVERAGE", "COW",
  "COWARD", "CRAB", "CRACK", "CRAFT", "CRANE", "CRASH", "CRAZY", "CREAM", "CREATE",
  "CREATION", "CREATIVE", "CREATOR", "CREATURE", "CREDIT", "CREEK", "CREW",
  "CRICKET", "CRIME", "CRIMINAL", "CRISIS", "CRISP", "CRITIC", "CRITICAL",
  "CRITICISM", "CRITICIZE", "CROP", "CROSS", "CROWD", "CROWDED", "CROWN", "CRUCIAL",
  "CRUDE", "CRUEL", "CRUSH", "CRY", "CULTIVATE", "CULTURE", "CUP", "CUPBOARD",
  "CURE", "CURIOSITY", "CURIOUS", "CURL", "CURRENCY", "CURRENT", "CURRICULUM",
  "CURSE", "CURTAIN", "CURVE", "CUSHION", "CUSTOM", "CUSTOMER", "CUT", "CYCLE",
  "DAILY", "DAIRY", "DAMAGE", "DAMP", "DANCE", "DANGER", "DANGEROUS", "DARE",
  "DARK", "DARKNESS", "DARLING", "DARN", "DASH", "DATA", "DATE", "DAUGHTER",
  "DAWN", "DAY", "DAYLIGHT", "DAZZLE", "DEAD", "DEAF", "DEAL", "DEALER", "DEAR",
  "DEATH", "DEBATE", "DEBT", "DECAY", "DECEMBER", "DECEIVE", "DECIDE", "DECISION",
  "DECISIVE", "DECLARE", "DECLINE", "DECORATE", "DECREASE", "DEDICATE", "DEED",
  "DEEP", "DEEPLY", "DEER", "DEFEAT", "DEFECT", "DEFEND", "DEFENSE", "DEFENSIVE",
  "DEFER", "DEFICIT", "DEFINE", "DEFINITE", "DEFINITION", "DEGREE", "DELAY",
  "DELETE", "DELIBERATE", "DELICATE", "DELICIOUS", "DELIGHT", "DELIVER", "DELIVERY",
  "DEMAND", "DEMOCRACY", "DEMOCRATIC", "DEMONSTRATE", "DEN", "DENIAL", "DENSE",
  "DENSITY", "DENTIST", "DENY", "DEPART", "DEPARTMENT", "DEPARTURE", "DEPEND",
  "DEPENDENT", "DEPICT", "DEPOSIT", "DEPRESSION", "DEPRIVE", "DEPTH", "DEPUTY",
  "DERIVE", "DESCEND", "DESCENDANT", "DESCENT", "DESCRIBE", "DESCRIPTION", "DESERT",
  "DESERVE", "DESIGN", "DESIRABLE", "DESIRE", "DESK", "DESPAIR", "DESPERATE",
  "DESPITE", "DESTROY", "DESTRUCTION", "DETAIL", "DETAILED", "DETECT", "DETER",
  "DETERMINATION", "DETERMINE", "DEVELOP", "DEVELOPMENT", "DEVICE", "DEVISE",
  "DEVOTE", "DIAGRAM", "DIAL", "DIAMETER", "DIAMOND", "DIARY", "DICE", "DID", "DIE",
  "DIFFER", "DIFFERENCE", "DIFFERENT", "DIFFICULT", "DIFFICULTY", "DIG", "DIGEST",
  "DIGITAL", "DIGNITY", "DILEMMA", "DILIGENT", "DIM", "DIMENSION", "DINE", "DINNER",
  "DIP", "DIPLOMA", "DIRECT", "DIRECTION", "DIRECTLY", "DIRECTOR", "DIRECTORY",
  "DIRT", "DIRTY", "DISABLED", "DISADVANTAGE", "DISAGREE", "DISAPPEAR", "DISAPPOINT",
  "DISAPPROVE", "DISARM", "DISASTER", "DISC", "DISCARD", "DISCERN", "DISCHARGE",
  "DISCIPLINE", "DISCLOSE", "DISCOMFORT", "DISCONNECT", "DISCONTENT", "DISCOURAGE",
  "DISCOVER", "DISCOVERY", "DISCUSS", "DISCUSSION", "DISEASE", "DISGUST", "DISH",
  "DISHONEST", "DISLIKE", "DISMISS", "DISORDER", "DISPLAY", "DISPOSE", "DISPUTE",
  "DISSOLVE", "DISTANCE", "DISTANT", "DISTINCT", "DISTINCTION", "DISTINGUISH",
  "DISTORT", "DISTRACT", "DISTRESS", "DISTRIBUTE", "DISTRIBUTION", "DISTRICT",
  "DISTURB", "DISTURBANCE", "DITCH", "DIVE", "DIVER", "DIVIDE", "DIVISION",
  "DIVORCE", "DIZZY", "DO", "DOCK", "DOCTOR", "DOCUMENT", "DOES", "DOG", "DOLL",
  "DOLLAR", "DOMAIN", "DOME", "DOMESTIC", "DOMINANT", "DOMINATE", "DONE", "DOOM",
  "DOOR", "DOORSTEP", "DOORWAY", "DOPE", "DORMITORY", "DOSE", "DOT", "DOUBLE",
  "DOUBT", "DOVE", "DOWN", "DOWNSTAIRS", "DOWNWARD", "DOZEN", "DRAFT", "DRAG",
  "DRAIN", "DRAMA", "DRAMATIC", "DRAW", "DRAWER", "DRAWING", "DREAD", "DREAM",
  "DRESS", "DRESSER", "DREW", "DRIBBLE", "DRIED", "DRIER", "DRIFT", "DRILL",
  "DRINK", "DRIP", "DRIVE", "DRIVER", "DRIVEWAY", "DRIVING", "DROP", "DROPPED",
  "DROUGHT", "DROVE", "DROWN", "DRUG", "DRUM", "DRUNK", "DRY", "DUCK", "DUE", "DULL",
  "DUMB", "DUMP", "DURING", "DUSK", "DUST", "DUTY", "DWELL", "DWELLING", "DYING",
  "DYNAMIC", "DYNAMICS", "EACH", "EAGER", "EAGLE", "EAR", "EARLY", "EARN",
  "EARNINGS", "EARTH", "EARTHQUAKE", "EASE", "EASILY", "EAST", "EASTERN", "EASY",
  "EAT", "ECCENTRIC", "ECHO", "ECLIPSE", "ECONOMIC", "ECONOMICS", "ECONOMY", "EDGE",
  "EDITOR", "EDUCATE", "EDUCATION", "EDUCATIONAL", "EFFECT", "EFFECTIVE",
  "EFFECTIVELY", "EFFICIENCY", "EFFICIENT", "EFFORT", "EGG", "EGO", "EIGHT",
  "EIGHTEEN", "EIGHTH", "EIGHTY", "EITHER", "ELABORATE", "ELASTIC", "ELBOW",
  "ELDER", "ELDERLY", "ELECT", "ELECTION", "ELECTRIC", "ELECTRICAL", "ELECTRICITY",
  "ELECTRON", "ELECTRONIC", "ELEGANT", "ELEMENT", "ELEMENTARY", "ELEPHANT",
  "ELEVATE", "ELEVATION", "ELEVATOR", "ELEVEN", "ELIGIBLE", "ELIMINATE", "ELITE",
  "ELSE", "ELSEWHERE", "ELUDE", "ELUSIVE", "EM", "EMAIL", "EMANATE", "EMBARK",
  "EMBARRASS", "EMBED", "EMBLEM", "EMBRACE", "EMERGE", "EMERGENCY", "EMERGING",
  "EMIGRATE", "EMINENT", "EMIT", "EMOTION", "EMOTIONAL", "EMPEROR", "EMPHASIS",
  "EMPHASIZE", "EMPIRE", "EMPLOY", "EMPLOYEE", "EMPLOYER", "EMPLOYMENT", "EMPTY",
  "ENABLE", "ENACT", "ENCLOSE", "ENCOUNTER", "ENCOURAGE", "END", "ENDANGER",
  "ENDEAVOR", "ENDING", "ENDLESS", "ENDORSE", "ENDOW", "ENDURANCE", "ENDURE",
  "ENEMY", "ENERGETIC", "ENERGY", "ENFORCE", "ENGAGE", "ENGAGEMENT", "ENGINE",
  "ENGINEER", "ENGINEERING", "ENGLISH", "ENHANCE", "ENJOY", "ENJOYMENT", "ENLARGE",
  "ENLIGHTEN", "ENORMOUS", "ENOUGH", "ENQUIRE", "ENQUIRY", "ENROLL", "ENSURE",
  "ENTER", "ENTERPRISE", "ENTERTAIN", "ENTERTAINMENT", "ENTHUSIASM", "ENTHUSIASTIC",
  "ENTIRE", "ENTIRELY", "ENTITLE", "ENTRANCE", "ENTREPRENEUR", "ENTRY", "ENVELOPE",
  "ENVIRONMENT", "ENVIRONMENTAL", "ENVIABLE", "ENVIOUS", "ENVY", "EPIC", "EPISODE",
  "EQUAL", "EQUALLY", "EQUATION", "EQUATOR", "EQUIP", "EQUIPMENT", "EQUITY",
  "EQUIVALENT", "ERA", "ERASE", "ERECT", "EROSION", "ERROR", "ERUPT", "ESCAPE",
  "ESPECIALLY", "ESSAY", "ESSENCE", "ESSENTIAL", "ESTABLISH", "ESTABLISHMENT",
  "ESTATE", "ESTIMATE", "ESTIMATED", "ETCETERA", "ETERNAL", "ETHICAL", "ETHICS",
  "ETHNIC", "EVALUATE", "EVALUATION", "EVAPORATE", "EVEN", "EVENING", "EVENLY",
  "EVENT", "EVENTUAL", "EVENTUALLY", "EVER", "EVERY", "EVERYBODY", "EVERYDAY",
  "EVERYONE", "EVERYTHING", "EVERYWHERE", "EVIDENCE", "EVIDENT", "EVIL", "EVOKE",
  "EVOLUTION", "EVOLVE", "EXACT", "EXACTLY", "EXAGGERATE", "EXAM", "EXAMINATION",
  "EXAMINE", "EXAMPLE", "EXCEED", "EXCELLENT", "EXCEPT", "EXCEPTION", "EXCEPTIONAL",
  "EXCESS", "EXCESSIVE", "EXCHANGE", "EXCITE", "EXCITED", "EXCITEMENT", "EXCITING",
  "EXCLAIM", "EXCLAMATION", "EXCLUDE", "EXCLUSIVE", "EXCURSION", "EXCUSE", "EXECUTE",
  "EXECUTION", "EXECUTIVE", "EXERCISE", "EXERT", "EXHALE", "EXHAUST", "EXHIBIT",
  "EXHIBITION", "EXILE", "EXIST", "EXISTENCE", "EXIT", "EXOTIC", "EXPAND",
  "EXPANSION", "EXPECT", "EXPECTATION", "EXPEDITION", "EXPEND", "EXPENDITURE",
  "EXPENSE", "EXPENSIVE", "EXPERIENCE", "EXPERIMENT", "EXPERIMENTAL", "EXPERT",
  "EXPIRE", "EXPLAIN", "EXPLANATION", "EXPLICIT", "EXPLODE", "EXPLOIT",
  "EXPLOITATION", "EXPLORE", "EXPLORATION", "EXPLORER", "EXPLOSION", "EXPLOSIVE",
  "EXPORT", "EXPOSE", "EXPOSITION", "EXPOSURE", "EXPRESS", "EXPRESSION",
  "EXPRESSIVE", "EXTEND", "EXTENSION", "EXTENSIVE", "EXTENT", "EXTENUATE",
  "EXTERIOR", "EXTERNAL", "EXTINCT", "EXTINCTION", "EXTINGUISH", "EXTOL", "EXTORT",
  "EXTRA", "EXTRACT", "EXTRACTION", "EXTRAORDINARY", "EXTRAVAGANT", "EXTREME",
  "EXTREMELY", "EYE", "EYEBROW", "EYELASH", "EYELID", "FABRIC", "FABRICATE",
  "FABULOUS", "FACE", "FACILITATE", "FACILITY", "FACT", "FACTION", "FACTOR",
  "FACTORY", "FACULTY", "FADE", "FAIL", "FAILURE", "FAINT", "FAIR", "FAIRLY",
  "FAIRY", "FAITH", "FAITHFUL", "FALL", "FALSE", "FAME", "FAMILIAR", "FAMILY",
  "FAMINE", "FAMOUS", "FAN", "FANCY", "FANTASY", "FAR", "FARE", "FARM", "FARMER",
  "FARTHER", "FASCINATE", "FASHION", "FASHIONABLE", "FAST", "FASTEN", "FAT",
  "FATAL", "FATE", "FATHER", "FATHOM", "FATIGUE", "FAULT", "FAVOR", "FAVORABLE",
  "FAVORITE", "FAWN", "FEAR", "FEARFUL", "FEARLESS", "FEASIBLE", "FEAST", "FEATHER",
  "FEATURE", "FEBRUARY", "FED", "FEDERAL", "FEDERATION", "FEE", "FEED", "FEEDBACK",
  "FEEL", "FEELING", "FEET", "FELL", "FELLOW", "FELLOWSHIP", "FELT", "FEMALE",
  "FEMININE", "FENCE", "FEND", "FERMENT", "FEROCIOUS", "FERRET", "FERRY", "FERTILE",
  "FERTILIZE", "FERTILIZER", "FESTIVAL", "FETCH", "FEVER", "FEW", "FIANCE",
  "FIANCEE", "FIBER", "FICTION", "FICTITIOUS", "FIDDLE", "FIELD", "FIERCE",
  "FIFTEEN", "FIFTH", "FIFTY", "FIGHT", "FIGHTER", "FIGURE", "FILE", "FILL", "FILM",
  "FILTER", "FILTH", "FINAL", "FINALLY", "FINANCE", "FINANCIAL", "FIND", "FINE",
  "FINGER", "FINISH", "FINITE", "FIRE", "FIREARM", "FIREPLACE", "FIREWORK", "FIRM",
  "FIRST", "FISCAL", "FISH", "FISHERMAN", "FISHING", "FISSION", "FISSURE", "FIST",
  "FIT", "FITNESS", "FIVE", "FIX", "FIXTURE", "FLAG", "FLAKE", "FLAME", "FLANK",
  "FLAP", "FLASH", "FLASK", "FLAT", "FLATTER", "FLAVOR", "FLEE", "FLEET", "FLESH",
  "FLEW", "FLEXIBLE", "FLICK", "FLIGHT", "FLING", "FLINT", "FLIP", "FLOAT", "FLOCK",
  "FLOOD", "FLOOR", "FLOUR", "FLOURISH", "FLOW", "FLOWER", "FLUID", "FLUNG",
  "FLUSH", "FLUTE", "FLY", "FOAM", "FOCUS", "FOG", "FOIL", "FOLD", "FOLK", "FOLLOW",
  "FOLLOWING", "FOLLOWER", "FOND", "FOOD", "FOOL", "FOOLISH", "FOOT", "FOOTBALL",
  "FOOTNOTE", "FOOTPATH", "FOOTSTEP", "FOR", "FORBID", "FORCE", "FORE", "FORECAST",
  "FOREFATHER", "FOREGO", "FOREHEAD", "FOREIGN", "FOREIGNER", "FOREMOST",
  "FORESEE", "FORESIGHT", "FOREST", "FOREVER", "FORFEIT", "FORGAVE", "FORGE",
  "FORGET", "FORGETFUL", "FORGIVE", "FORGIVEN", "FORGIVENESS", "FORGIVING", "FORK",
  "FORM", "FORMAL", "FORMAT", "FORMATION", "FORMER", "FORMERLY", "FORMIDABLE",
  "FORMULA", "FORMULATE", "FORT", "FORTH", "FORTHCOMING", "FORTNIGHT", "FORTRESS",
  "FORTUNATE", "FORTUNE", "FORTY", "FORUM", "FORWARD", "FOSSIL", "FOSTER", "FOUGHT",
  "FOUL", "FOUND", "FOUNDATION", "FOUNDER", "FOUNTAIN", "FOUR", "FOURTEEN",
  "FOURTH", "FOWL", "FOX", "FRACTION", "FRACTURE", "FRAGILE", "FRAGMENT",
  "FRAGRANCE", "FRAGRANT", "FRAIL", "FRAME", "FRANK", "FRANTIC", "FRATERNITY",
  "FRAUD", "FREE", "FREEDOM", "FREEZE", "FREIGHT", "FRENCH", "FRENZY", "FREQUENT",
  "FREQUENTLY", "FRESH", "FRESHMAN", "FRICTION", "FRIDAY", "FRIEND", "FRIENDLY",
  "FRIENDSHIP", "FRIGHT", "FRIGHTEN", "FRIGHTFUL", "FRINGE", "FRISK", "FRISKY",
  "FRIVOLOUS", "FROCK", "FROG", "FROM", "FRONT", "FRONTIER", "FROST", "FROZEN",
  "FRUIT", "FRUSTRATE", "FRY", "FUEL", "FULFILL", "FULL", "FULLY", "FUMBLE", "FUN",
  "FUNCTION", "FUNCTIONAL", "FUND", "FUNDAMENTAL", "FUNERAL", "FUNGI", "FUNK",
  "FUNNEL", "FUNNY", "FUR", "FURIOUS", "FURNACE", "FURNISH", "FURNITURE", "FURTHER",
  "FURTHEST", "FURY", "FUSE", "FUSION", "FUSS", "FUTURE", "FUZZY", "GAB", "GADGET",
  "GAIN", "GAIT", "GALAXY", "GALLERY", "GALLON", "GALLOP", "GALORE", "GALVANIZE",
  "GAMBLE", "GAME", "GAMMA", "GANG", "GAP", "GARAGE", "GARBAGE", "GARDEN",
  "GARDENER", "GARLIC", "GARMENT", "GARNISH", "GARRISON", "GAS", "GASEOUS",
  "GASOLINE", "GASP", "GATE", "GATEWAY", "GATHER", "GAUGE", "GAUNT", "GAZE", "GEAR",
  "GEL", "GEM", "GENDER", "GENERAL", "GENERALLY", "GENERATE", "GENERATION",
  "GENERATOR", "GENEROUS", "GENETIC", "GENIUS", "GENRE", "GENTLE", "GENTLEMAN",
  "GENTLEWOMAN", "GENUINE", "GEOGRAPHY", "GEOLOGY", "GEOMETRY", "GERM", "GERMAN",
  "GESTURE", "GET", "GHOST", "GIANT", "GIFT", "GIFTED", "GIGANTIC", "GIGGLE",
  "GILDED", "GILT", "GINGER", "GIRL", "GIRTH", "GIVE", "GIVEN", "GIVING", "GLACIER",
  "GLAD", "GLAMOUR", "GLANCE", "GLAND", "GLARE", "GLASS", "GLASSY", "GLAZE",
  "GLEAM", "GLEAN", "GLIDE", "GLIMMER", "GLIMPSE", "GLINT", "GLISTEN", "GLITTER",
  "GLOBE", "GLOOM", "GLOOMY", "GLORIOUS", "GLORY", "GLOSS", "GLOSSARY", "GLOSSY",
  "GLOVE", "GLOW", "GLUE", "GLUM", "GLUT", "GLUTTON", "GLUTTONY", "GNASH", "GNAT",
  "GNAW", "GNOME", "GO", "GOAL", "GOAT", "GOBLET", "GOD", "GODDESS", "GODFATHER",
  "GODMOTHER", "GODSON", "GOES", "GOGGLES", "GOING", "GOLD", "GOLDEN", "GOLF",
  "GONE", "GONG", "GOOD", "GOODBYE", "GOODNESS", "GOODS", "GOODWILL", "GOOSE",
  "AFRAID", "ALMOST", "BECAUSE", "BETWEEN", "BOTTLE", "BRIDGE", "CAREFUL", "CENTER",
  "CHOOSE", "CHURCH", "CLOTHES", "COFFEE", "COUNTRY", "DANGER", "DOLLAR", "EASILY",
  "ENGINE", "ENOUGH", "EXCEPT", "FAMOUS", "FEATHER", "FOREST", "FORGET", "GENTLE",
  "HAMMER", "HEALTH", "HUNGRY", "ISLAND", "JACKET", "JOURNEY", "KINDLY", "LADDER",
  "LEADER", "LOVELY", "MIRROR", "MOUNTAIN", "NEPHEW", "NIBBLE", "OFFICE", "PARENT",
  "PILLOW", "POISON", "POLITE", "PUPPET", "QUICKLY", "QUIETLY", "RIVER", "SAFETY",
  "SHADOW", "SILENT", "SILVER", "SPOON", "STRONG", "SUNDAY", "THIRSTY", "TICKET",
  "VALLEY", "VILLAGE", "WEATHER", "WRITER"
];

const dictClass7 = [
  "ABBREVIATE", "ABUNDANCE", "ACCESSIBLE", "ACCOMMODATION", "ACCOMPLISHMENT", "ACCUMULATE", "ACCURATE", "ACKNOWLEDGMENT",
  "ACQUISITION", "ADAPTATION", "ADEQUATE", "ADJACENT", "ADJUSTMENT", "ADMINISTER", "ADVANTAGEOUS", "ADVOCATE",
  "AESTHETIC", "AFFILIATE", "AGGRAVATE", "AGGREGATE", "ALGORITHM", "ALLEGIANCE", "ALLOCATE", "ALTERNATIVE",
  "AMBIGUITY", "AMBITIOUS", "AMENDMENT", "AMPLIFY", "ANALOGY", "ANALYSIS", "ANONYMOUS", "ANTICIPATE",
  "APPARATUS", "APPARENT", "APPLICATION", "APPRECIATE", "APPREHEND", "APPROPRIATE", "APPROXIMATE", "ARBITRARY",
  "ARCHITECTURE", "ARTICULATE", "ASPECT", "ASSEMBLE", "ASSERTION", "ASSESSMENT", "ASSISTANCE", "ASSOCIATION",
  "ATMOSPHERE", "ATTAINMENT", "ATTITUDE", "ATTRIBUTE", "AUTHENTIC", "AUTHORITY", "AUTOMATION", "AUXILIARY",
  "AVAILABLE", "AVERAGE", "AWARENESS", "BACKGROUND", "BALANCE", "BARRIER", "BENEFICIAL", "BIODIVERSITY",
  "BOUNDARY", "BROADCAST", "CALCULATE", "CAPACITY", "CATEGORY", "CELEBRATE", "CHALLENGE", "CHARACTERISTIC",
  "CHRONOLOGICAL", "CIRCUMSTANCE", "CIVILIZATION", "CLARIFICATION", "CLASSIFICATION", "COALITION", "COGNITIVE", "COHERENCE"
];

const dictClass8 = [
  "ABANDONMENT", "ABERRATION", "ABSTAIN", "ABSTRACT", "ABUNDANTLY", "ACCELERATE", "ACCESSIBILITY", "ACCLIMATION",
  "ACCOMPANIMENT", "ACCOUNTABILITY", "ACCREDITATION", "ACCULTURATION", "ACCUMULATION", "ACCURACY", "ACCUSATION", "ACCUSTOM",
  "ACHIEVABLE", "ACKNOWLEDGING", "ACOUSTIC", "ACQUAINTANCE", "ACQUISITION", "ACRIMONIOUS", "ACTIVATION", "ADAPTABILITY",
  "ADDITIONAL", "ADEQUATELY", "ADHERENCE", "ADJOINING", "ADJOURNMENT", "ADJUSTABLE", "ADMINISTRATIVE", "ADMIRABLE",
  "ADMISSIBLE", "ADMITTANCE", "ADMONITION", "ADOLESCENCE", "ADOPTABLE", "ADORATION", "ADULTERATION", "ADVANCEMENT",
  "ADVENTUROUS", "ADVERSARY", "ADVERSITY", "ADVERTISEMENT", "ADVISABLE", "ADVOCACY", "AERONAUTICS", "AESTHETICS",
  "AFFABILITY", "AFFECTATION", "AFFILIATION", "AFFIRMATION", "AFFIRMATIVE", "AFFLICTION", "AFFLUENCE", "AFTERMATH",
  "AGGRAVATION", "AGGREGATION", "AGGRESSION", "AGGRESSIVE", "AGREEMENT", "AGRICULTURAL", "ALGORITHM", "ALIENABLE",
  "ALIGNMENT", "ALLEGATION", "ALLEGIANCE", "ALLEVIATE", "ALLOCATION", "ALLOWANCE", "ALLITERATION", "ALLUSIVE",
  "ALTERATION", "ALTERNATIVE", "ALTRUISTIC", "AMALGAMATE", "AMBIGUOUS", "AMBIVALENCE", "AMELIORATE", "AMENABLE"
];

const dictClass9 = [
 "ADVENTURE", "AMAZING", "BELIEVE", "CELEBRATE", "DIFFERENT", "EVERYTHING", "FEATHER", "GARDEN", "HAPPINESS", "IMAGINE", "JOURNEY", "KNOWLEDGE", "LIBRARY", "MOUNTAIN", "NEIGHBOR", "ORCHESTRA", "PRACTICE", "QUESTION", "REMEMBER", "SCIENCE", "TOGETHER", "UMBRELLA", "VACATION", "WEATHER", "YESTERDAY",
  "ABSOLUTELY", "BEAUTIFUL", "CHALLENGE", "DANGEROUS", "EXPERIENCE", "FAVORITE", "GOVERNMENT", "HOSPITAL", "IMPORTANT", "LANGUAGE", "MATERIAL", "NECESSARY", "OPERATE", "PARTICULAR", "RECOGNIZE", "SEPARATE", "TRADITION", "UNDERSTAND", "VALUABLE", "WONDERFUL",
   "ACCOMMODATE", "BENEFICIAL", "COMMUNICATE", "DETERMINATION", "EFFICIENT", "FREQUENTLY", "GENEROUS", "HESITATE", "INDIVIDUAL", "JUDGMENT", "KNOWLEDGEABLE", "LEGISLATION", "MYSTERIOUS", "NEGOTIATE", "OPPORTUNITY", "POSSESSION", "QUALIFICATION", "RECOMMEND", "SUCCESSFUL", "THOROUGHLY",
  "ABUNDANT", "ACCURATE", "ADAPT", "ANALYZE", "BARRIER", "BENEFIT", "BOUNDARY",
  "CAPABLE", "CAPACITY", "CAUTIOUS", "COLLAPSE", "COMBINE", "COMPLEX", "CONSUME",
  "CONTRAST", "CRUCIAL", "DECLINE", "DEFEND", "DEPOSIT", "DETECT", "DEVIATE",
  "DISPLAY", "DRASTIC", "EFFICIENT", "ELEMENT", "EMERGE", "EQUIVALENT", "ESTABLISH",
  "EVIDENT", "EXPAND", "EXPOSE", "EXTRACT", "FLEXIBLE", "FUNCTION", "GENUINE",
  "GRADUAL", "HOSTILE", "IDENTICAL", "IMPACT", "INDICATE", "INITIAL", "INTENSE",
  "INTERNAL", "ISOLATE", "LOGICAL", "MARGIN", "MAXIMUM", "MINIMUM", "MODIFY", "NEGATIVE"
];

const dictClass10 = [
  "AMBIGUITY", "COMPREHENSIVE", "DEBILITATING", "ELOQUENCE", "FLAMBOYANT", "GRATIFICATION", "HYPOTHETICAL", "INCONCEIVABLE", "JURISDICTION", "METICULOUSLY", "NONCHALANT", "OSTENTATIOUS", "PROXIMITY", "QUINTESSENTIAL", "REPERCUSSION",
  "ABSTRACT", "ADVOCATE", "AMBIGUOUS", "ANALOGY", "ARBITRARY", "BIAS", "COHERENT",
    "COINCIDE", "COMMODITY", "COMPATIBLE", "CONCEDE", "CONCISE", "CONCURRENT",
    "CONFINES", "CONSEQUENCE", "CONSTITUTE", "CONTRADICT", "CONVENE", "CRITERION",
    "CRUCIAL", "CURRENCY", "DATABASE", "DECIPHER", "DEDUCE", "DENOTE", "DERIVE",
    "DIMENSION", "DISCRETE", "DISCRIMINATE", "DISPLACE", "DIVERSE", "DOMAIN", "DYNAMIC",
    "ELIMINATE", "EMPIRICAL", "ENFORCE", "ENTITY", "ETHICAL", "EXPLICIT", "FACILITATE",
    "FINITE", "FLUCTUATE", "FORMULATE", "HIERARCHY", "HYPOTHESIS", "IDEOLOGY",
    "IMPLEMENT", "IMPLICIT", "INCENTIVE", "INCIDENCE",
  "APPROPRIATE", "CHARACTERISTIC", "CONSEQUENTLY", "DISTINGUISH", "ENCOURAGEMENT", "FOUNDATION", "GUARANTEE", "IMMEDIATELY", "JUSTIFICATION", "MAINTENANCE", "NEVERTHELESS", "OCCURRENCE", "PHILOSOPHY", "REPRESENTATIVE", "SIGNIFICANT",

  "ABERRATION", "ACQUIESCE", "ADVERSITY", "AESTHETIC", "AMBIVALENT", "ANACHRONISM",
  "BENEVOLENT", "CAPITULATE", "CHAUVINISM", "COGNIZANT", "COLLUSION", "COMPLACENT",
  "CONSTRUE", "DEFERENCE", "DELETERIOUS", "DEMAGOGUE", "DICHOTOMY", "DIDACTIC",
  "DISPARATE", "ELOQUENT", "EMPATHY", "EPHEMERAL", "EPITOME", "EQUANIMITY",
  "ESOTERIC", "EUPHEMISM", "EXACERBATE", "EXCULPATE", "FASTIDIOUS", "FORTUITOUS",
  "GREGARIOUS", "HEDONIST", "HYPOCRITICAL", "IMPETUOUS", "INCISIVE", "INDIGENOUS",
  "INNOCUOUS", "INTRACTABLE", "INTRANSIGENT", "JUGGERNAUT", "LUCID", "MAGNANIMOUS",
  "METICULOUS", "NEBULOUS", "NIHILISM", "OBSEQUIOUS", "PARADIGM", "PERFUNCTORY",
  "PRAGMATIC", "PRECARIOUS"
];

window.VOCABULARY = {
  "Age < 8": [...dictKG1, ...dictKG2, ...dictClass1],
  "Age 8-12": [...dictClass1, ...dictClass2, ...dictClass3],
  "Age 12-16": [...dictClass3, ...dictClass4, ...dictClass5, ...dictClass6, ...dictClass7, ...dictClass8],
  "Age 16-20": [...dictClass6, ...dictClass5, ...dictClass9, ...dictClass10],
  "Age 20+": [...dictClass6, ...dictClass5, ...dictClass9, ...dictClass10] // Or add more advanced words here
};
